//! Babel (JavaScript) code generator for RustScript

use crate::parser::*;
use crate::mapping::{get_node_mapping, get_node_mapping_by_visitor, get_field_mapping};

/// Generator for Babel plugin JavaScript code
pub struct BabelGenerator {
    output: String,
    indent: usize,
    /// Maps parameter names to their aliases (e.g., "func" -> "node")
    param_aliases: std::collections::HashMap<String, String>,
}

impl BabelGenerator {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            param_aliases: std::collections::HashMap::new(),
        }
    }

    /// Generate JavaScript code for a Babel plugin
    pub fn generate(&mut self, program: &Program) -> String {
        match &program.decl {
            TopLevelDecl::Plugin(plugin) => self.gen_plugin(plugin),
            TopLevelDecl::Writer(writer) => self.gen_writer(writer),
        }
        std::mem::take(&mut self.output)
    }

    fn emit(&mut self, s: &str) {
        self.output.push_str(s);
    }

    fn emit_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("  ");
        }
    }

    fn emit_line(&mut self, s: &str) {
        self.emit_indent();
        self.emit(s);
        self.emit("\n");
    }

    fn gen_plugin(&mut self, plugin: &PluginDecl) {
        // Generate Babel plugin module structure
        self.emit_line("// Generated by RustScript compiler");
        self.emit_line("// Do not edit manually");
        self.emit_line("");
        self.emit_line("module.exports = function({ types: t }) {");
        self.indent += 1;

        // Generate helper structs as classes
        for item in &plugin.body {
            if let PluginItem::Struct(s) = item {
                self.gen_struct_class(s);
            }
        }

        // Generate helper functions
        for item in &plugin.body {
            if let PluginItem::Function(f) = item {
                if !f.name.starts_with("visit_") {
                    self.gen_helper_function(f);
                }
            }
        }

        // Generate visitor state initialization
        self.emit_line("");
        self.emit_line("let state = {};");
        self.emit_line("");

        // Generate return with visitor
        self.emit_line("return {");
        self.indent += 1;
        self.emit_line("visitor: {");
        self.indent += 1;

        // Generate visitor methods
        let mut first = true;
        for item in &plugin.body {
            if let PluginItem::Function(f) = item {
                if f.name.starts_with("visit_") {
                    if !first {
                        self.emit(",\n");
                    }
                    first = false;
                    self.gen_visitor_method(f);
                }
            }
        }

        self.emit("\n");
        self.indent -= 1;
        self.emit_line("}");
        self.indent -= 1;
        self.emit_line("};");

        self.indent -= 1;
        self.emit_line("};");
    }

    fn gen_writer(&mut self, writer: &WriterDecl) {
        // Generate writer as a class that builds output
        self.emit_line("// Generated by RustScript compiler");
        self.emit_line("// Do not edit manually");
        self.emit_line("");
        self.emit(&format!("class {} {{\n", writer.name));
        self.indent += 1;

        // Constructor
        self.emit_line("constructor() {");
        self.indent += 1;
        self.emit_line("this._output = [];");
        self.emit_line("this._indentLevel = 0;");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        // CodeBuilder methods
        self.emit_line("append(s) { this._output.push(s); }");
        self.emit_line("newline() { this._output.push('\\n'); }");
        self.emit_line("indent() { this._indentLevel++; }");
        self.emit_line("dedent() { this._indentLevel--; }");
        self.emit_line("toString() { return this._output.join(''); }");
        self.emit_line("");

        // Generate helper functions and visitor methods
        for item in &writer.body {
            if let PluginItem::Function(f) = item {
                self.gen_method(f);
            }
        }

        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");
        self.emit(&format!("module.exports = {};\n", writer.name));
    }

    fn gen_struct_class(&mut self, s: &StructDecl) {
        self.emit_line("");
        self.emit(&format!("  class {} {{\n", s.name));
        self.indent += 1;

        // Constructor
        let params: Vec<&str> = s.fields.iter().map(|f| f.name.as_str()).collect();
        self.emit(&format!("  constructor({}) {{\n", params.join(", ")));
        self.indent += 1;
        for field in &s.fields {
            self.emit_line(&format!("this.{} = {};", field.name, field.name));
        }
        self.indent -= 1;
        self.emit_line("}");

        self.indent -= 1;
        self.emit_line("}");
    }

    fn gen_helper_function(&mut self, f: &FnDecl) {
        self.emit_line("");
        let params: Vec<String> = f.params.iter().map(|p| p.name.clone()).collect();
        self.emit_line(&format!("function {}({}) {{", f.name, params.join(", ")));
        self.indent += 1;
        self.gen_block(&f.body);
        self.indent -= 1;
        self.emit_line("}");
    }

    fn gen_method(&mut self, f: &FnDecl) {
        let params: Vec<String> = f.params.iter().map(|p| p.name.clone()).collect();
        self.emit_line(&format!("{}({}) {{", f.name, params.join(", ")));
        self.indent += 1;
        self.gen_block(&f.body);
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");
    }

    fn gen_visitor_method(&mut self, f: &FnDecl) {
        // Convert visit_call_expression to CallExpression
        let node_type = self.visitor_name_to_babel_type(&f.name);

        self.emit_indent();
        self.emit(&format!("{}(path) {{", node_type));
        self.emit("\n");
        self.indent += 1;

        // Add node alias and track the parameter rename
        self.emit_line("const node = path.node;");

        // Set up parameter alias: original param name -> "node"
        if !f.params.is_empty() {
            let original_name = &f.params[0].name;
            self.param_aliases.insert(original_name.clone(), "node".to_string());
        }

        self.gen_block(&f.body);

        // Clear the alias after generating the method
        if !f.params.is_empty() {
            self.param_aliases.remove(&f.params[0].name);
        }

        self.indent -= 1;
        self.emit_indent();
        self.emit("}");
    }

    fn visitor_name_to_babel_type(&self, name: &str) -> String {
        // Use mapping module: visit_call_expression -> CallExpression
        if let Some(mapping) = get_node_mapping_by_visitor(name) {
            return mapping.babel.to_string();
        }

        // Fallback: convert snake_case to PascalCase
        let stripped = name.strip_prefix("visit_").unwrap_or(name);
        stripped
            .split('_')
            .map(|s| {
                let mut chars = s.chars();
                match chars.next() {
                    None => String::new(),
                    Some(c) => c.to_uppercase().chain(chars).collect(),
                }
            })
            .collect()
    }

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.gen_stmt(stmt);
        }
    }

    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(let_stmt) => {
                self.emit_indent();
                if let_stmt.mutable {
                    self.emit("let ");
                } else {
                    self.emit("const ");
                }
                self.emit(&let_stmt.name);
                self.emit(" = ");
                self.gen_expr(&let_stmt.init);
                self.emit(";\n");
            }
            Stmt::Const(const_stmt) => {
                self.emit_indent();
                self.emit("const ");
                self.emit(&const_stmt.name);
                self.emit(" = ");
                self.gen_expr(&const_stmt.init);
                self.emit(";\n");
            }
            Stmt::Expr(expr_stmt) => {
                self.emit_indent();
                self.gen_expr(&expr_stmt.expr);
                self.emit(";\n");
            }
            Stmt::If(if_stmt) => {
                self.emit_indent();
                self.emit("if (");
                self.gen_expr(&if_stmt.condition);
                self.emit(") {\n");
                self.indent += 1;
                self.gen_block(&if_stmt.then_branch);
                self.indent -= 1;

                for (cond, block) in &if_stmt.else_if_branches {
                    self.emit_indent();
                    self.emit("} else if (");
                    self.gen_expr(cond);
                    self.emit(") {\n");
                    self.indent += 1;
                    self.gen_block(block);
                    self.indent -= 1;
                }

                if let Some(else_block) = &if_stmt.else_branch {
                    self.emit_indent();
                    self.emit("} else {\n");
                    self.indent += 1;
                    self.gen_block(else_block);
                    self.indent -= 1;
                }

                self.emit_line("}");
            }
            Stmt::For(for_stmt) => {
                self.emit_indent();
                self.emit(&format!("for (const {} of ", for_stmt.var));
                self.gen_expr(&for_stmt.iter);
                self.emit(") {\n");
                self.indent += 1;
                self.gen_block(&for_stmt.body);
                self.indent -= 1;
                self.emit_line("}");
            }
            Stmt::While(while_stmt) => {
                self.emit_indent();
                self.emit("while (");
                self.gen_expr(&while_stmt.condition);
                self.emit(") {\n");
                self.indent += 1;
                self.gen_block(&while_stmt.body);
                self.indent -= 1;
                self.emit_line("}");
            }
            Stmt::Loop(loop_stmt) => {
                self.emit_line("while (true) {");
                self.indent += 1;
                self.gen_block(&loop_stmt.body);
                self.indent -= 1;
                self.emit_line("}");
            }
            Stmt::Return(ret) => {
                self.emit_indent();
                if let Some(value) = &ret.value {
                    self.emit("return ");
                    self.gen_expr(value);
                    self.emit(";\n");
                } else {
                    self.emit("return;\n");
                }
            }
            Stmt::Break(_) => {
                self.emit_line("break;");
            }
            Stmt::Continue(_) => {
                self.emit_line("continue;");
            }
            Stmt::Match(match_stmt) => {
                self.gen_match_stmt(match_stmt);
            }
            Stmt::Traverse(traverse_stmt) => {
                self.gen_traverse_stmt(traverse_stmt);
            }
        }
    }

    fn gen_traverse_stmt(&mut self, traverse_stmt: &crate::parser::TraverseStmt) {
        match &traverse_stmt.kind {
            crate::parser::TraverseKind::Inline(inline) => {
                // Generate inline visitor object
                self.emit_indent();
                self.emit("const __nestedVisitor = {\n");
                self.indent += 1;

                // Generate state
                if !inline.state.is_empty() {
                    self.emit_indent();
                    self.emit("state: {\n");
                    self.indent += 1;
                    for let_stmt in &inline.state {
                        self.emit_indent();
                        self.emit(&let_stmt.name);
                        self.emit(": ");
                        self.gen_expr(&let_stmt.init);
                        self.emit(",\n");
                    }
                    self.indent -= 1;
                    self.emit_indent();
                    self.emit("},\n");
                }

                // Generate visitor methods
                for method in &inline.methods {
                    // Convert visit_xxx to PascalCase node type
                    let node_type = self.visitor_method_to_node_type(&method.name);
                    self.emit_indent();
                    self.emit(&format!("{}(path) {{\n", node_type));
                    self.indent += 1;

                    // Generate method body
                    // First, alias the node
                    self.emit_indent();
                    if !method.params.is_empty() {
                        self.emit(&format!("const {} = path.node;\n", method.params[0].name));
                    }

                    self.gen_block(&method.body);
                    self.indent -= 1;
                    self.emit_indent();
                    self.emit("},\n");
                }

                self.indent -= 1;
                self.emit_indent();
                self.emit("};\n");

                // Generate traversal call
                self.emit_indent();
                self.gen_expr(&traverse_stmt.target);
                self.emit(".traverse(__nestedVisitor);\n");
            }
            crate::parser::TraverseKind::Delegated(visitor_name) => {
                // Generate delegation to another visitor
                self.emit_indent();
                self.gen_expr(&traverse_stmt.target);
                self.emit(&format!(".traverse({});\n", visitor_name));
            }
        }
    }

    fn visitor_method_to_node_type(&self, method_name: &str) -> String {
        // Use mapping module: visit_xxx_yyy -> XxxYyy
        if let Some(mapping) = get_node_mapping_by_visitor(method_name) {
            return mapping.babel.to_string();
        }

        // Fallback: convert visit_xxx_yyy to XxxYyy
        if let Some(stripped) = method_name.strip_prefix("visit_") {
            stripped
                .split('_')
                .map(|part| {
                    let mut chars = part.chars();
                    match chars.next() {
                        None => String::new(),
                        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                    }
                })
                .collect()
        } else {
            method_name.to_string()
        }
    }

    fn gen_match_stmt(&mut self, match_stmt: &MatchStmt) {
        // Convert match to switch or if-else chain
        // For now, generate if-else chain for flexibility
        let mut first = true;
        for arm in &match_stmt.arms {
            self.emit_indent();
            if first {
                self.emit("if (");
                first = false;
            } else {
                self.emit("} else if (");
            }
            self.gen_pattern_condition(&arm.pattern, &match_stmt.scrutinee);
            self.emit(") {\n");
            self.indent += 1;
            self.emit_indent();
            self.gen_expr(&arm.body);
            self.emit(";\n");
            self.indent -= 1;
        }
        self.emit_line("}");
    }

    fn gen_pattern_condition(&mut self, pattern: &Pattern, scrutinee: &Expr) {
        match pattern {
            Pattern::Literal(lit) => {
                self.gen_expr(scrutinee);
                self.emit(" === ");
                self.gen_literal(lit);
            }
            Pattern::Ident(name) => {
                // Binding pattern - always true, but we bind the value
                self.emit("true");
                // The binding is handled separately
                let _ = name; // suppress unused warning
            }
            Pattern::Wildcard => {
                self.emit("true");
            }
            Pattern::Or(patterns) => {
                self.emit("(");
                for (i, p) in patterns.iter().enumerate() {
                    if i > 0 {
                        self.emit(" || ");
                    }
                    self.gen_pattern_condition(p, scrutinee);
                }
                self.emit(")");
            }
            Pattern::Struct { name, fields } => {
                // Type check with field pattern matching
                // Use mapping to get the correct Babel type checker
                let checker = get_node_mapping(name)
                    .map(|m| m.babel_checker.to_string())
                    .unwrap_or_else(|| format!("is{}", name));
                self.emit(&format!("t.{}(", checker));
                self.gen_expr(scrutinee);
                self.emit(")");
                for (field_name, field_pattern) in fields {
                    self.emit(" && ");
                    // Create nested scrutinee for field
                    let field_access = format!("{}.{}", self.expr_to_string(scrutinee), field_name);
                    self.gen_pattern_condition_str(field_pattern, &field_access);
                }
            }
        }
    }

    fn gen_pattern_condition_str(&mut self, pattern: &Pattern, scrutinee: &str) {
        match pattern {
            Pattern::Literal(lit) => {
                self.emit(scrutinee);
                self.emit(" === ");
                self.gen_literal(lit);
            }
            Pattern::Ident(_) => {
                self.emit("true");
            }
            Pattern::Wildcard => {
                self.emit("true");
            }
            _ => {
                self.emit("true"); // Simplified for now
            }
        }
    }

    fn expr_to_string(&self, expr: &Expr) -> String {
        let mut gen = BabelGenerator::new();
        gen.gen_expr(expr);
        gen.output
    }

    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Literal(lit) => self.gen_literal(lit),
            Expr::Ident(ident) => {
                // Handle special cases
                match ident.name.as_str() {
                    "self" => self.emit("this"),
                    // Handle Default::default() which the hoister uses as a placeholder
                    name if name.starts_with("Default::default") => self.emit("undefined"),
                    _ => {
                        // Check if this identifier has an alias
                        let output = if let Some(alias) = self.param_aliases.get(&ident.name) {
                            alias.clone()
                        } else {
                            ident.name.clone()
                        };
                        self.emit(&output);
                    }
                }
            }
            Expr::Binary(bin) => {
                self.emit("(");
                self.gen_expr(&bin.left);
                self.emit(&format!(" {} ", self.binary_op_to_js(&bin.op)));
                self.gen_expr(&bin.right);
                self.emit(")");
            }
            Expr::Unary(un) => {
                match un.op {
                    UnaryOp::Not => {
                        self.emit("!");
                        self.gen_expr(&un.operand);
                    }
                    UnaryOp::Neg => {
                        self.emit("-");
                        self.gen_expr(&un.operand);
                    }
                    UnaryOp::Deref => {
                        // In JS, dereference is a no-op
                        self.gen_expr(&un.operand);
                    }
                    UnaryOp::Ref | UnaryOp::RefMut => {
                        // In JS, references are passed directly
                        self.gen_expr(&un.operand);
                    }
                }
            }
            Expr::Call(call) => {
                // Check for matches! macro
                if let Expr::Ident(ident) = call.callee.as_ref() {
                    if ident.name == "matches!" && call.args.len() >= 2 {
                        self.gen_matches_macro(&call.args[0], &call.args[1]);
                        return;
                    }
                    // Check for panic! macro -> throw new Error()
                    if ident.name == "panic!" {
                        self.emit("throw new Error(");
                        if let Some(arg) = call.args.first() {
                            self.gen_expr(arg);
                        } else {
                            self.emit("\"panic\"");
                        }
                        self.emit(")");
                        return;
                    }
                    // Check for Default::default() -> undefined or appropriate default
                    if ident.name == "Default::default()" || ident.name == "Default::default" {
                        self.emit("undefined");
                        return;
                    }
                }
                // Also check as a standalone identifier (no parens in name)
                if let Expr::Ident(ident) = call.callee.as_ref() {
                    if ident.name.starts_with("Default::default") {
                        self.emit("undefined");
                        return;
                    }
                }

                // Check if this is a method call that should be a property in JS
                if let Expr::Member(mem) = call.callee.as_ref() {
                    let prop = &mem.property;
                    // len() -> .length (property, no parens)
                    if prop == "len" {
                        self.gen_expr(&mem.object);
                        self.emit(".length");
                        return;
                    }
                    // is_empty() -> .length === 0
                    if prop == "is_empty" {
                        self.emit("(");
                        self.gen_expr(&mem.object);
                        self.emit(".length === 0)");
                        return;
                    }
                    // clone() -> just the value (no-op in JS)
                    if prop == "clone" {
                        self.gen_expr(&mem.object);
                        return;
                    }
                    // insert(0, x) -> unshift(x) when first arg is 0
                    if prop == "insert" && call.args.len() == 2 {
                        if let Expr::Literal(Literal::Int(0)) = &call.args[0] {
                            self.gen_expr(&mem.object);
                            self.emit(".unshift(");
                            self.gen_expr(&call.args[1]);
                            self.emit(")");
                            return;
                        }
                        // Otherwise use splice for insert at arbitrary index
                        self.gen_expr(&mem.object);
                        self.emit(".splice(");
                        self.gen_expr(&call.args[0]);
                        self.emit(", 0, ");
                        self.gen_expr(&call.args[1]);
                        self.emit(")");
                        return;
                    }
                    // to_string() -> no-op in JS (strings are already strings)
                    if prop == "to_string" {
                        self.gen_expr(&mem.object);
                        return;
                    }
                    // visit_children(self) -> Babel auto-traverses, so this is a no-op
                    // We emit nothing since Babel handles traversal automatically
                    if prop == "visit_children" {
                        self.emit("/* Babel auto-traverses */");
                        return;
                    }
                    // visit_with(self) -> for manual iteration, also skip
                    if prop == "visit_with" {
                        self.emit("/* manual traversal handled by Babel */");
                        return;
                    }
                }

                self.gen_expr(&call.callee);
                self.emit("(");
                for (i, arg) in call.args.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }
                    self.gen_expr(arg);
                }
                self.emit(")");
            }
            Expr::Member(mem) => {
                self.gen_expr(&mem.object);
                // Convert Rust-style method names to JS
                let js_name = self.convert_method_name(&mem.property);
                if !js_name.is_empty() {
                    self.emit(".");
                    // Map SWC field names back to Babel field names
                    let babel_field = match js_name.as_str() {
                        "sym" => "name", // Ident.sym -> Identifier.name
                        _ => &js_name,
                    };
                    self.emit(babel_field);
                }
                // If empty (like .clone()), we skip the member access entirely
            }
            Expr::Index(idx) => {
                self.gen_expr(&idx.object);
                self.emit("[");
                self.gen_expr(&idx.index);
                self.emit("]");
            }
            Expr::StructInit(init) => {
                // Check if this is an AST node type that should use Babel builders
                if let Some(babel_builder) = self.ast_type_to_babel_builder(&init.name) {
                    self.gen_babel_node_construction(&babel_builder, &init.fields);
                } else {
                    // Generate as object literal
                    self.emit("{ ");
                    for (i, (name, value)) in init.fields.iter().enumerate() {
                        if i > 0 {
                            self.emit(", ");
                        }
                        self.emit(name);
                        self.emit(": ");
                        self.gen_expr(value);
                    }
                    self.emit(" }");
                }
            }
            Expr::VecInit(vec) => {
                self.emit("[");
                for (i, elem) in vec.elements.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }
                    self.gen_expr(elem);
                }
                self.emit("]");
            }
            Expr::If(if_expr) => {
                self.emit("(");
                self.gen_expr(&if_expr.condition);
                self.emit(" ? ");
                // Simplified - assumes single expression in then branch
                if let Some(stmt) = if_expr.then_branch.stmts.first() {
                    if let Stmt::Expr(expr_stmt) = stmt {
                        self.gen_expr(&expr_stmt.expr);
                    }
                }
                self.emit(" : ");
                if let Some(else_block) = &if_expr.else_branch {
                    if let Some(stmt) = else_block.stmts.first() {
                        if let Stmt::Expr(expr_stmt) = stmt {
                            self.gen_expr(&expr_stmt.expr);
                        }
                    }
                } else {
                    self.emit("undefined");
                }
                self.emit(")");
            }
            Expr::Match(match_expr) => {
                // Generate as IIFE with switch
                self.emit("(() => { ");
                let mut first = true;
                for arm in &match_expr.arms {
                    if first {
                        self.emit("if (");
                        first = false;
                    } else {
                        self.emit(" else if (");
                    }
                    self.gen_pattern_condition(&arm.pattern, &match_expr.scrutinee);
                    self.emit(") { return ");
                    self.gen_expr(&arm.body);
                    self.emit("; }");
                }
                self.emit(" })()");
            }
            Expr::Closure(closure) => {
                self.emit("(");
                self.emit(&closure.params.join(", "));
                self.emit(") => ");
                self.gen_expr(&closure.body);
            }
            Expr::Ref(ref_expr) => {
                // In JS, just pass the value directly
                self.gen_expr(&ref_expr.expr);
            }
            Expr::Deref(deref) => {
                // In JS, dereference is a no-op
                self.gen_expr(&deref.expr);
            }
            Expr::Assign(assign) => {
                // Statement lowering: *node = ... becomes path.replaceWith(...)
                // This applies to any deref assignment, not just "node"
                if let Expr::Deref(deref) = assign.target.as_ref() {
                    if let Expr::Ident(_ident) = deref.expr.as_ref() {
                        // Any dereference assignment in a visitor should use path.replaceWith
                        self.emit("path.replaceWith(");
                        self.gen_expr(&assign.value);
                        self.emit(")");
                        return;
                    }
                }
                // Regular assignment
                self.gen_expr(&assign.target);
                self.emit(" = ");
                self.gen_expr(&assign.value);
            }
            Expr::CompoundAssign(compound) => {
                self.gen_expr(&compound.target);
                self.emit(&format!(" {}= ", self.compound_op_to_js(&compound.op)));
                self.gen_expr(&compound.value);
            }
            Expr::Range(range) => {
                // Generate array range (simplified)
                self.emit("/* range not fully supported */");
                if let Some(start) = &range.start {
                    self.gen_expr(start);
                }
                self.emit("..");
                if let Some(end) = &range.end {
                    self.gen_expr(end);
                }
            }
            Expr::Paren(inner) => {
                self.emit("(");
                self.gen_expr(inner);
                self.emit(")");
            }
        }
    }

    fn gen_literal(&mut self, lit: &Literal) {
        match lit {
            Literal::String(s) => {
                self.emit(&format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")));
            }
            Literal::Int(n) => {
                self.emit(&n.to_string());
            }
            Literal::Float(n) => {
                self.emit(&n.to_string());
            }
            Literal::Bool(b) => {
                self.emit(if *b { "true" } else { "false" });
            }
            Literal::Null => {
                self.emit("null");
            }
        }
    }

    fn binary_op_to_js(&self, op: &BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            BinaryOp::Div => "/",
            BinaryOp::Mod => "%",
            BinaryOp::Eq => "===",
            BinaryOp::NotEq => "!==",
            BinaryOp::Lt => "<",
            BinaryOp::Gt => ">",
            BinaryOp::LtEq => "<=",
            BinaryOp::GtEq => ">=",
            BinaryOp::And => "&&",
            BinaryOp::Or => "||",
        }
    }

    fn compound_op_to_js(&self, op: &CompoundAssignOp) -> &'static str {
        match op {
            CompoundAssignOp::AddAssign => "+",
            CompoundAssignOp::SubAssign => "-",
            CompoundAssignOp::MulAssign => "*",
            CompoundAssignOp::DivAssign => "/",
        }
    }

    fn convert_method_name(&self, name: &str) -> String {
        // Convert Rust-style methods to JS equivalents
        match name {
            "starts_with" => "startsWith".to_string(),
            "ends_with" => "endsWith".to_string(),
            "contains" => "includes".to_string(),
            "len" => "length".to_string(),
            "is_empty" => "length === 0".to_string(), // Special case
            "to_uppercase" => "toUpperCase".to_string(),
            "to_lowercase" => "toLowerCase".to_string(),
            "push" => "push".to_string(),
            "clone" => "".to_string(), // Clone is no-op in JS, strip it
            "unwrap_or" => "??".to_string(), // Will need special handling
            // RustScript to Babel field mappings
            "stmts" => "body".to_string(), // BlockStatement.stmts -> BlockStatement.body
            "is_if_statement" => "isIfStatement".to_string(),
            "is_abstract" => "abstract".to_string(),
            _ => name.to_string(),
        }
    }

    /// Generate matches! macro as Babel type checks
    fn gen_matches_macro(&mut self, scrutinee: &Expr, pattern: &Expr) {
        self.emit("(");
        self.gen_matches_pattern(scrutinee, pattern);
        self.emit(")");
    }

    /// Recursively generate type checks for a pattern
    fn gen_matches_pattern(&mut self, scrutinee: &Expr, pattern: &Expr) {
        match pattern {
            Expr::StructInit(init) => {
                // Generate t.isType(scrutinee, { field: value, ... })
                let type_name = &init.name;

                // Use mapping to get the correct Babel type checker
                let checker = get_node_mapping(type_name)
                    .map(|m| m.babel_checker.to_string())
                    .unwrap_or_else(|| format!("is{}", type_name));
                self.emit(&format!("t.{}(", checker));
                self.gen_expr(scrutinee);
                self.emit(")");

                // Generate field checks
                for (field_name, field_pattern) in &init.fields {
                    self.emit(" && ");

                    // Create the field access expression
                    let field_scrutinee = format!("{}.{}", self.expr_to_string(scrutinee), field_name);

                    match field_pattern {
                        Expr::Literal(Literal::String(s)) => {
                            // Simple string equality check
                            self.emit(&format!("{} === \"{}\"", field_scrutinee, s));
                        }
                        Expr::StructInit(_) => {
                            // Nested struct pattern - recurse
                            // We need to create a fake Ident expression for the field access
                            let field_expr = Expr::Ident(IdentExpr {
                                name: field_scrutinee.clone(),
                                span: crate::lexer::Span::new(0, 0, 0, 0),
                            });
                            self.gen_matches_pattern(&field_expr, field_pattern);
                        }
                        _ => {
                            // Other patterns - generate equality
                            self.emit(&field_scrutinee);
                            self.emit(" === ");
                            self.gen_expr(field_pattern);
                        }
                    }
                }
            }
            Expr::Ident(ident) => {
                // Check if this is a type name (AST node type)
                // If so, generate t.isTypeName(scrutinee)
                let type_name = &ident.name;

                // Use mapping to get the correct Babel type checker
                if let Some(mapping) = get_node_mapping(type_name) {
                    self.emit(&format!("t.{}(", mapping.babel_checker));
                    self.gen_expr(scrutinee);
                    self.emit(")");
                } else {
                    // Fallback: assume it's an AST type and generate isTypeName
                    self.emit(&format!("t.is{}(", type_name));
                    self.gen_expr(scrutinee);
                    self.emit(")");
                }
            }
            _ => {
                // For other patterns (literals, etc.), generate equality check
                self.gen_expr(scrutinee);
                self.emit(" === ");
                self.gen_expr(pattern);
            }
        }
    }

    /// Convert RustScript AST type names to Babel builder function names
    fn ast_type_to_babel_builder(&self, type_name: &str) -> Option<String> {
        // Use mapping module to get the Babel builder name
        // The builder name is typically camelCase of the type name
        if let Some(mapping) = get_node_mapping(type_name) {
            // Convert PascalCase to camelCase for builder function
            let babel_name = mapping.babel;
            let mut chars = babel_name.chars();
            let builder = match chars.next() {
                None => return None,
                Some(c) => c.to_lowercase().collect::<String>() + chars.as_str(),
            };
            return Some(builder);
        }

        // Fallback for types not in mapping (like literals)
        let builder = match type_name {
            "StringLiteral" => "stringLiteral",
            "NumericLiteral" => "numericLiteral",
            "BooleanLiteral" => "booleanLiteral",
            "NullLiteral" => "nullLiteral",
            "SpreadElement" => "spreadElement",
            "VariableDeclarator" => "variableDeclarator",
            "CatchClause" => "catchClause",
            "ObjectProperty" => "objectProperty",
            "ObjectMethod" => "objectMethod",
            "ClassMethod" => "classMethod",
            "ClassProperty" => "classProperty",
            "RestElement" => "restElement",
            "AssignmentPattern" => "assignmentPattern",
            _ => return None,
        };
        Some(builder.to_string())
    }

    /// Generate Babel node construction call
    fn gen_babel_node_construction(&mut self, builder: &str, fields: &[(String, Expr)]) {
        self.emit(&format!("t.{}(", builder));

        // Different builders take different argument orders
        // We'll generate based on common patterns
        match builder {
            "identifier" => {
                // t.identifier(name)
                if let Some((_, value)) = fields.iter().find(|(k, _)| k == "name") {
                    self.gen_expr(value);
                }
            }
            "stringLiteral" => {
                // t.stringLiteral(value)
                if let Some((_, value)) = fields.iter().find(|(k, _)| k == "value") {
                    self.gen_expr(value);
                }
            }
            "numericLiteral" => {
                // t.numericLiteral(value)
                if let Some((_, value)) = fields.iter().find(|(k, _)| k == "value") {
                    self.gen_expr(value);
                }
            }
            "booleanLiteral" => {
                // t.booleanLiteral(value)
                if let Some((_, value)) = fields.iter().find(|(k, _)| k == "value") {
                    self.gen_expr(value);
                }
            }
            "callExpression" => {
                // t.callExpression(callee, arguments)
                if let Some((_, callee)) = fields.iter().find(|(k, _)| k == "callee") {
                    self.gen_expr(callee);
                }
                self.emit(", ");
                if let Some((_, args)) = fields.iter().find(|(k, _)| k == "arguments") {
                    self.gen_expr(args);
                } else {
                    self.emit("[]");
                }
            }
            "memberExpression" => {
                // t.memberExpression(object, property, computed, optional)
                if let Some((_, obj)) = fields.iter().find(|(k, _)| k == "object") {
                    self.gen_expr(obj);
                }
                self.emit(", ");
                if let Some((_, prop)) = fields.iter().find(|(k, _)| k == "property") {
                    self.gen_expr(prop);
                }
                // Add computed flag if present
                if let Some((_, computed)) = fields.iter().find(|(k, _)| k == "computed") {
                    self.emit(", ");
                    self.gen_expr(computed);
                }
            }
            "expressionStatement" => {
                // t.expressionStatement(expression)
                if let Some((_, expr)) = fields.iter().find(|(k, _)| k == "expression") {
                    self.gen_expr(expr);
                }
            }
            "returnStatement" => {
                // t.returnStatement(argument)
                if let Some((_, arg)) = fields.iter().find(|(k, _)| k == "argument") {
                    self.gen_expr(arg);
                } else {
                    self.emit("null");
                }
            }
            "blockStatement" => {
                // t.blockStatement(body)
                if let Some((_, body)) = fields.iter().find(|(k, _)| k == "body") {
                    self.gen_expr(body);
                } else {
                    self.emit("[]");
                }
            }
            "variableDeclaration" => {
                // t.variableDeclaration(kind, declarations)
                if let Some((_, kind)) = fields.iter().find(|(k, _)| k == "kind") {
                    self.gen_expr(kind);
                } else {
                    self.emit("\"const\"");
                }
                self.emit(", ");
                if let Some((_, decls)) = fields.iter().find(|(k, _)| k == "declarations") {
                    self.gen_expr(decls);
                } else {
                    self.emit("[]");
                }
            }
            "variableDeclarator" => {
                // t.variableDeclarator(id, init)
                if let Some((_, id)) = fields.iter().find(|(k, _)| k == "id") {
                    self.gen_expr(id);
                }
                if let Some((_, init)) = fields.iter().find(|(k, _)| k == "init") {
                    self.emit(", ");
                    self.gen_expr(init);
                }
            }
            "jsxElement" => {
                // t.jsxElement(openingElement, closingElement, children)
                if let Some((_, open)) = fields.iter().find(|(k, _)| k == "openingElement") {
                    self.gen_expr(open);
                }
                self.emit(", ");
                if let Some((_, close)) = fields.iter().find(|(k, _)| k == "closingElement") {
                    self.gen_expr(close);
                } else {
                    self.emit("null");
                }
                self.emit(", ");
                if let Some((_, children)) = fields.iter().find(|(k, _)| k == "children") {
                    self.gen_expr(children);
                } else {
                    self.emit("[]");
                }
            }
            "jsxIdentifier" => {
                // t.jsxIdentifier(name)
                if let Some((_, name)) = fields.iter().find(|(k, _)| k == "name") {
                    self.gen_expr(name);
                }
            }
            "jsxAttribute" => {
                // t.jsxAttribute(name, value)
                if let Some((_, name)) = fields.iter().find(|(k, _)| k == "name") {
                    self.gen_expr(name);
                }
                if let Some((_, value)) = fields.iter().find(|(k, _)| k == "value") {
                    self.emit(", ");
                    self.gen_expr(value);
                }
            }
            "jsxExpressionContainer" => {
                // t.jsxExpressionContainer(expression)
                if let Some((_, expr)) = fields.iter().find(|(k, _)| k == "expression") {
                    self.gen_expr(expr);
                }
            }
            _ => {
                // For other builders, generate as object with fields
                self.emit("{ ");
                for (i, (name, value)) in fields.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }
                    self.emit(name);
                    self.emit(": ");
                    self.gen_expr(value);
                }
                self.emit(" }");
            }
        }

        self.emit(")");
    }
}

impl Default for BabelGenerator {
    fn default() -> Self {
        Self::new()
    }
}
