//! SWC (Rust) code generator for RustScript

use crate::parser::*;
use crate::mapping::{get_node_mapping, get_node_mapping_by_visitor, get_field_mapping, get_pattern_check};
use super::type_context::{TypeEnvironment, TypeContext, get_swc_variant_in_context, get_typed_field_mapping, map_rustscript_to_swc};

/// Generator for SWC plugin Rust code
pub struct SwcGenerator {
    output: String,
    indent: usize,
    /// Maps RustScript parameter names to SWC names (e.g., "node" -> "n")
    param_renames: std::collections::HashMap<String, String>,
    /// Plugin name for generating nested visitors
    plugin_name: String,
    /// Hoisted inline visitor structs
    hoisted_visitors: Vec<String>,
    /// Type environment for flow-sensitive typing
    type_env: TypeEnvironment,
    /// Variables captured from outer scope (need self. prefix)
    captured_vars: std::collections::HashSet<String>,
}

impl SwcGenerator {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            param_renames: std::collections::HashMap::new(),
            plugin_name: String::new(),
            hoisted_visitors: Vec::new(),
            type_env: TypeEnvironment::new(),
            captured_vars: std::collections::HashSet::new(),
        }
    }

    /// Generate Rust code for an SWC plugin
    pub fn generate(&mut self, program: &Program) -> String {
        // Emit file header
        self.emit_line("// Generated by RustScript compiler");
        self.emit_line("// Do not edit manually");
        self.emit_line("");
        self.emit_line("use swc_common::{Span, DUMMY_SP};");
        self.emit_line("use swc_ecma_ast::*;");
        self.emit_line("use swc_ecma_visit::{VisitMut, VisitMutWith};");
        self.emit_line("");

        match &program.decl {
            TopLevelDecl::Plugin(plugin) => self.gen_plugin(plugin),
            TopLevelDecl::Writer(writer) => self.gen_writer(writer),
            TopLevelDecl::Interface(_iface) => {
                // TODO: Generate TypeScript interface type
            }
        }

        // Emit hoisted inline visitors at the end
        if !self.hoisted_visitors.is_empty() {
            self.emit_line("");
            self.emit_line("// Hoisted inline visitors for traverse blocks");
            let visitors = std::mem::take(&mut self.hoisted_visitors);
            for visitor in visitors {
                self.emit(&visitor);
                self.emit_line("");
            }
        }

        std::mem::take(&mut self.output)
    }

    fn emit(&mut self, s: &str) {
        self.output.push_str(s);
    }

    fn emit_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
    }

    fn emit_line(&mut self, s: &str) {
        self.emit_indent();
        self.emit(s);
        self.emit("\n");
    }

    fn gen_plugin(&mut self, plugin: &PluginDecl) {
        // Generate struct definitions first
        for item in &plugin.body {
            if let PluginItem::Struct(s) = item {
                self.gen_struct(s);
            }
        }

        // Generate enum definitions
        for item in &plugin.body {
            if let PluginItem::Enum(e) = item {
                self.gen_enum(e);
            }
        }

        // Generate the main plugin struct
        self.emit_line(&format!("pub struct {} {{", plugin.name));
        self.indent += 1;
        self.emit_line("// Plugin state");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        // Generate impl block with helper functions
        self.emit_line(&format!("impl {} {{", plugin.name));
        self.indent += 1;

        self.emit_line("pub fn new() -> Self {");
        self.indent += 1;
        self.emit_line("Self {}");
        self.indent -= 1;
        self.emit_line("}");

        // Generate helper functions (non-visitor)
        for item in &plugin.body {
            if let PluginItem::Function(f) = item {
                if !f.name.starts_with("visit_") {
                    self.emit_line("");
                    self.gen_helper_function(f);
                }
            }
        }

        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        // Generate VisitMut impl
        self.emit_line(&format!("impl VisitMut for {} {{", plugin.name));
        self.indent += 1;

        for item in &plugin.body {
            if let PluginItem::Function(f) = item {
                if f.name.starts_with("visit_") {
                    self.gen_visitor_method(f);
                }
            }
        }

        self.indent -= 1;
        self.emit_line("}");
    }

    fn gen_writer(&mut self, writer: &WriterDecl) {
        // For writers, use Visit instead of VisitMut
        self.emit_line("use swc_ecma_visit::Visit;");
        self.emit_line("");

        // Generate structs
        for item in &writer.body {
            if let PluginItem::Struct(s) = item {
                self.gen_struct(s);
            }
        }

        // Generate the writer struct with CodeBuilder
        self.emit_line(&format!("pub struct {} {{", writer.name));
        self.indent += 1;
        self.emit_line("output: String,");
        self.emit_line("indent_level: usize,");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        // Generate impl block
        self.emit_line(&format!("impl {} {{", writer.name));
        self.indent += 1;

        self.emit_line("pub fn new() -> Self {");
        self.indent += 1;
        self.emit_line("Self {");
        self.indent += 1;
        self.emit_line("output: String::new(),");
        self.emit_line("indent_level: 0,");
        self.indent -= 1;
        self.emit_line("}");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        // CodeBuilder methods
        self.emit_line("fn append(&mut self, s: &str) {");
        self.indent += 1;
        self.emit_line("self.output.push_str(s);");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        self.emit_line("fn newline(&mut self) {");
        self.indent += 1;
        self.emit_line("self.output.push('\\n');");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        self.emit_line("fn indent(&mut self) {");
        self.indent += 1;
        self.emit_line("self.indent_level += 1;");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        self.emit_line("fn dedent(&mut self) {");
        self.indent += 1;
        self.emit_line("self.indent_level -= 1;");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        self.emit_line("pub fn finish(self) -> String {");
        self.indent += 1;
        self.emit_line("self.output");
        self.indent -= 1;
        self.emit_line("}");

        // Generate helper functions
        for item in &writer.body {
            if let PluginItem::Function(f) = item {
                if !f.name.starts_with("visit_") {
                    self.emit_line("");
                    self.gen_helper_function(f);
                }
            }
        }

        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        // Generate Visit impl
        self.emit_line(&format!("impl Visit for {} {{", writer.name));
        self.indent += 1;

        for item in &writer.body {
            if let PluginItem::Function(f) = item {
                if f.name.starts_with("visit_") {
                    self.gen_visit_method(f);
                }
            }
        }

        self.indent -= 1;
        self.emit_line("}");
    }

    fn gen_struct(&mut self, s: &StructDecl) {
        self.emit_line("#[derive(Debug, Clone)]");
        self.emit_line(&format!("pub struct {} {{", s.name));
        self.indent += 1;
        for field in &s.fields {
            self.emit_indent();
            self.emit(&format!("pub {}: {},\n", field.name, self.type_to_rust(&field.ty)));
        }
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");
    }

    fn gen_enum(&mut self, e: &EnumDecl) {
        self.emit_line("#[derive(Debug, Clone)]");
        self.emit_line(&format!("pub enum {} {{", e.name));
        self.indent += 1;
        for variant in &e.variants {
            self.emit_indent();
            if let Some(fields) = &variant.fields {
                let types: Vec<String> = fields.iter().map(|t| self.type_to_rust(t)).collect();
                self.emit(&format!("{}({}),\n", variant.name, types.join(", ")));
            } else {
                self.emit(&format!("{},\n", variant.name));
            }
        }
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");
    }

    fn gen_helper_function(&mut self, f: &FnDecl) {
        let pub_str = if f.is_pub { "pub " } else { "" };
        let params: Vec<String> = f.params.iter().map(|p| {
            format!("{}: {}", p.name, self.type_to_rust(&p.ty))
        }).collect();

        let ret_type = f.return_type.as_ref()
            .map(|t| format!(" -> {}", self.type_to_rust(t)))
            .unwrap_or_default();

        self.emit_line(&format!("{}fn {}({}){} {{", pub_str, f.name, params.join(", "), ret_type));
        self.indent += 1;

        // Track parameter types in the environment
        self.type_env.push_scope();
        for param in &f.params {
            let param_ctx = self.type_from_ast(&param.ty);
            self.type_env.define(&param.name, param_ctx);
        }

        self.gen_block(&f.body);

        self.type_env.pop_scope();
        self.indent -= 1;
        self.emit_line("}");
    }

    fn gen_visitor_method(&mut self, f: &FnDecl) {
        let swc_name = self.visitor_name_to_swc(&f.name);
        let swc_type = self.visitor_name_to_swc_type(&f.name);

        self.emit_line("");
        self.emit_line(&format!("fn {}(&mut self, n: &mut {}) {{", swc_name, swc_type));
        self.indent += 1;

        // Set up parameter renames for visitor methods
        // The first parameter (typically "node") maps to "n"
        if let Some(first_param) = f.params.first() {
            self.param_renames.insert(first_param.name.clone(), "n".to_string());
        }

        // Track the parameter's type in the environment
        // Both "n" and the original parameter name should map to the swc_type
        self.type_env.push_scope();
        let param_ctx = TypeContext {
            rustscript_type: swc_type.clone(),
            swc_type: swc_type.clone(),
            kind: super::type_context::SwcTypeKind::Struct,
            known_variant: None,
            needs_deref: false,
        };
        self.type_env.define("n", param_ctx.clone());
        if let Some(first_param) = f.params.first() {
            self.type_env.define(&first_param.name, param_ctx);
        }

        // Generate body
        self.gen_block(&f.body);

        // Clear environment and renames
        self.type_env.pop_scope();
        self.param_renames.clear();

        self.indent -= 1;
        self.emit_line("}");
    }

    fn gen_visit_method(&mut self, f: &FnDecl) {
        // For Visit (read-only), parameters are & not &mut
        let swc_name = self.visitor_name_to_swc(&f.name);
        let swc_type = self.visitor_name_to_swc_type(&f.name);

        self.emit_line("");
        self.emit_line(&format!("fn {}(&mut self, n: &{}) {{", swc_name, swc_type));
        self.indent += 1;

        self.gen_block(&f.body);

        self.indent -= 1;
        self.emit_line("}");
    }

    fn visitor_name_to_swc(&self, name: &str) -> String {
        // Use mapping module: visit_call_expression -> visit_mut_call_expr
        if let Some(mapping) = get_node_mapping_by_visitor(name) {
            return mapping.swc_visitor.to_string();
        }
        // Fallback for unknown visitor methods
        let stripped = name.strip_prefix("visit_").unwrap_or(name);
        format!("visit_mut_{}", self.to_swc_node_name(stripped))
    }

    fn visitor_name_to_swc_type(&self, name: &str) -> String {
        // Use mapping module to get the SWC type for a visitor method
        if let Some(mapping) = get_node_mapping_by_visitor(name) {
            return mapping.swc.to_string();
        }
        let stripped = name.strip_prefix("visit_").unwrap_or(name);
        self.rustscript_to_swc_type(stripped)
    }

    fn to_swc_node_name(&self, name: &str) -> String {
        // Convert snake_case RustScript node names to SWC visitor method suffixes
        // Try to find a mapping by converting snake_case to PascalCase
        let pascal = name.split('_')
            .map(|part| {
                let mut chars = part.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                }
            })
            .collect::<String>();

        if let Some(mapping) = get_node_mapping(&pascal) {
            // Extract the suffix from swc_visitor (e.g., "visit_mut_call_expr" -> "call_expr")
            mapping.swc_visitor
                .strip_prefix("visit_mut_")
                .unwrap_or(&mapping.swc_visitor)
                .to_string()
        } else {
            // Fallback: apply common transformations
            name.replace("_expression", "_expr")
                .replace("_statement", "_stmt")
                .replace("_declaration", "_decl")
        }
    }

    fn rustscript_to_swc_type(&self, name: &str) -> String {
        // Convert RustScript node names to SWC AST types using mapping module
        // Handle both snake_case and PascalCase inputs

        // First try direct lookup (PascalCase)
        if let Some(mapping) = get_node_mapping(name) {
            return mapping.swc.to_string();
        }

        // Try converting snake_case to PascalCase
        let pascal: String = name.split('_')
            .map(|s| {
                let mut chars = s.chars();
                match chars.next() {
                    None => String::new(),
                    Some(c) => c.to_uppercase().chain(chars).collect(),
                }
            })
            .collect();

        if let Some(mapping) = get_node_mapping(&pascal) {
            return mapping.swc.to_string();
        }

        // Fallback: return the PascalCase conversion
        pascal
    }

    fn type_to_rust(&self, ty: &Type) -> String {
        match ty {
            Type::Primitive(name) => {
                match name.as_str() {
                    "Str" => "String".to_string(),
                    "()" => "()".to_string(),
                    _ => name.clone(),
                }
            }
            Type::Reference { mutable, inner } => {
                let inner_type = self.type_to_rust(inner);
                if *mutable {
                    format!("&mut {}", inner_type)
                } else {
                    format!("&{}", inner_type)
                }
            }
            Type::Container { name, type_args } => {
                let args: Vec<String> = type_args.iter().map(|t| self.type_to_rust(t)).collect();
                format!("{}<{}>", name, args.join(", "))
            }
            Type::Named(name) => {
                // Map RustScript AST types to SWC types
                // Don't lowercase - preserve original case for user-defined types
                self.rustscript_to_swc_type(name)
            }
            Type::Array { element } => {
                format!("Vec<{}>", self.type_to_rust(element))
            }
            Type::Tuple(types) => {
                let inner: Vec<String> = types.iter().map(|t| self.type_to_rust(t)).collect();
                format!("({})", inner.join(", "))
            }
            Type::Optional(inner) => {
                format!("Option<{}>", self.type_to_rust(inner))
            }
            Type::Unit => "()".to_string(),
        }
    }

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.gen_stmt(stmt);
        }
    }

    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(let_stmt) => {
                // Determine the type: use explicit annotation if available, else infer
                let var_type = if let Some(ty) = &let_stmt.ty {
                    // Use explicit type annotation
                    self.type_from_ast(ty)
                } else {
                    // Infer the type from the initializer expression
                    self.infer_type(&let_stmt.init)
                };

                self.emit_indent();
                if let_stmt.mutable {
                    self.emit("let mut ");
                } else {
                    self.emit("let ");
                }
                self.emit(&let_stmt.name);
                // Don't emit type annotations for internal temp variables
                // The type environment tracking is what matters
                self.emit(" = ");
                self.gen_expr(&let_stmt.init);
                self.emit(";\n");

                // Track the variable's type in the environment
                self.type_env.define(&let_stmt.name, var_type);
            }
            Stmt::Const(const_stmt) => {
                self.emit_indent();
                self.emit("const ");
                self.emit(&const_stmt.name);
                if let Some(ty) = &const_stmt.ty {
                    self.emit(&format!(": {}", self.type_to_rust(ty)));
                }
                self.emit(" = ");
                self.gen_expr(&const_stmt.init);
                self.emit(";\n");
            }
            Stmt::Expr(expr_stmt) => {
                self.emit_indent();
                self.gen_expr(&expr_stmt.expr);
                self.emit(";\n");
            }
            Stmt::If(if_stmt) => {
                // Check for if-let pattern first
                if let Some(pattern) = &if_stmt.pattern {
                    self.gen_if_let_stmt(if_stmt, pattern);
                } else if let Some((var_name, type_name)) = self.extract_matches_pattern(&if_stmt.condition) {
                    // Check if condition is matches!(var, Type)
                    // Look up the variable's type to determine the correct context
                    let var_type = self.type_env.lookup(&var_name)
                        .map(|ctx| ctx.swc_type.clone())
                        .unwrap_or_else(|| "Expr".to_string());

                    // Generate if let with type narrowing using context
                    let (swc_enum, swc_variant, swc_struct) = get_swc_variant_in_context(&type_name, &var_type);
                    #[cfg(debug_assertions)]
                    eprintln!("[swc] matches!({}, {}) -> var_type={}, enum={}, variant={}, struct={}",
                        var_name, type_name, var_type, swc_enum, swc_variant, swc_struct);

                    self.emit_indent();
                    // Handle nested patterns like Expr::Lit(Lit::Str(x))
                    let extra_close = if swc_variant.contains('(') { ")" } else { "" };
                    self.emit(&format!("if let {}::{}({}){} = &{} {{\n",
                        swc_enum, swc_variant, var_name, extra_close, var_name));

                    self.indent += 1;
                    self.type_env.push_scope();

                    // Shadow the variable with narrowed type
                    let narrowed_ctx = TypeContext::narrowed(&type_name, &swc_struct);
                    self.type_env.define(&var_name, narrowed_ctx);

                    self.gen_block(&if_stmt.then_branch);

                    self.type_env.pop_scope();
                    self.indent -= 1;

                    // Handle else-if branches - each might also be a matches! pattern
                    for (cond, block) in &if_stmt.else_if_branches {
                        if let Some((else_var_name, else_type_name)) = self.extract_matches_pattern(cond) {
                            // This else-if is also a matches! pattern
                            let else_var_type = self.type_env.lookup(&else_var_name)
                                .map(|ctx| ctx.swc_type.clone())
                                .unwrap_or_else(|| "Expr".to_string());

                            let (else_swc_enum, else_swc_variant, else_swc_struct) =
                                get_swc_variant_in_context(&else_type_name, &else_var_type);

                            #[cfg(debug_assertions)]
                            eprintln!("[swc] else if matches!({}, {}) -> var_type={}, enum={}, variant={}, struct={}",
                                else_var_name, else_type_name, else_var_type, else_swc_enum, else_swc_variant, else_swc_struct);

                            self.emit_indent();
                            // Handle nested patterns like Expr::Lit(Lit::Str(x))
                            let else_extra_close = if else_swc_variant.contains('(') { ")" } else { "" };
                            self.emit(&format!("}} else if let {}::{}({}){} = &{} {{\n",
                                else_swc_enum, else_swc_variant, else_var_name, else_extra_close, else_var_name));

                            self.indent += 1;
                            self.type_env.push_scope();

                            let else_narrowed_ctx = TypeContext::narrowed(&else_type_name, &else_swc_struct);
                            self.type_env.define(&else_var_name, else_narrowed_ctx);

                            self.gen_block(block);

                            self.type_env.pop_scope();
                            self.indent -= 1;
                        } else {
                            // Regular else-if condition
                            self.emit_indent();
                            self.emit("} else if ");
                            self.gen_expr(cond);
                            self.emit(" {\n");
                            self.indent += 1;
                            self.gen_block(block);
                            self.indent -= 1;
                        }
                    }

                    // Handle final else branch
                    if let Some(else_block) = &if_stmt.else_branch {
                        self.emit_indent();
                        self.emit("} else {\n");
                        self.indent += 1;
                        self.gen_block(else_block);
                        self.indent -= 1;
                    }

                    self.emit_line("}");
                } else {
                    // Standard if statement
                    self.emit_indent();
                    self.emit("if ");
                    self.gen_expr(&if_stmt.condition);
                    self.emit(" {\n");
                    self.indent += 1;
                    self.gen_block(&if_stmt.then_branch);
                    self.indent -= 1;

                    for (cond, block) in &if_stmt.else_if_branches {
                        self.emit_indent();
                        self.emit("} else if ");
                        self.gen_expr(cond);
                        self.emit(" {\n");
                        self.indent += 1;
                        self.gen_block(block);
                        self.indent -= 1;
                    }

                    if let Some(else_block) = &if_stmt.else_branch {
                        self.emit_indent();
                        self.emit("} else {\n");
                        self.indent += 1;
                        self.gen_block(else_block);
                        self.indent -= 1;
                    }

                    self.emit_line("}");
                }
            }
            Stmt::Match(match_stmt) => {
                self.emit_indent();
                self.emit("match ");
                self.gen_expr(&match_stmt.scrutinee);
                self.emit(" {\n");
                self.indent += 1;
                for arm in &match_stmt.arms {
                    self.emit_indent();
                    self.gen_pattern(&arm.pattern);
                    self.emit(" => ");
                    self.gen_expr(&arm.body);
                    self.emit(",\n");
                }
                self.indent -= 1;
                self.emit_line("}");
            }
            Stmt::For(for_stmt) => {
                self.emit_indent();
                self.emit(&format!("for {} in ", for_stmt.var));
                self.gen_expr(&for_stmt.iter);
                self.emit(" {\n");
                self.indent += 1;

                // Infer the type of the loop variable from the iterator
                self.type_env.push_scope();
                let iter_type = self.infer_type(&for_stmt.iter);
                let elem_type = self.get_element_type(&iter_type);
                #[cfg(debug_assertions)]
                eprintln!("[swc] for {} in {:?} -> iter_type={:?}, elem_type={:?}",
                    for_stmt.var, for_stmt.iter, iter_type, elem_type);
                self.type_env.define(&for_stmt.var, elem_type);

                self.gen_block(&for_stmt.body);

                self.type_env.pop_scope();
                self.indent -= 1;
                self.emit_line("}");
            }
            Stmt::While(while_stmt) => {
                // Check if condition is matches!(var, Type)
                if let Some((var_name, type_name)) = self.extract_matches_pattern(&while_stmt.condition) {
                    // Look up the variable's type to determine the correct context
                    let var_type = self.type_env.lookup(&var_name)
                        .map(|ctx| ctx.swc_type.clone())
                        .unwrap_or_else(|| "Expr".to_string());

                    // Generate while let with type narrowing using context
                    let (swc_enum, swc_variant, swc_struct) = get_swc_variant_in_context(&type_name, &var_type);

                    self.emit_indent();
                    self.emit(&format!("while let {}::{}({}) = {} {{\n",
                        swc_enum, swc_variant, var_name, var_name));

                    self.indent += 1;
                    self.type_env.push_scope();

                    // Shadow the variable with narrowed type
                    let narrowed_ctx = TypeContext::narrowed(&type_name, &swc_struct);
                    self.type_env.define(&var_name, narrowed_ctx);

                    self.gen_block(&while_stmt.body);

                    self.type_env.pop_scope();
                    self.indent -= 1;
                    self.emit_line("}");
                } else {
                    // Standard while loop
                    self.emit_indent();
                    self.emit("while ");
                    self.gen_expr(&while_stmt.condition);
                    self.emit(" {\n");
                    self.indent += 1;
                    self.gen_block(&while_stmt.body);
                    self.indent -= 1;
                    self.emit_line("}");
                }
            }
            Stmt::Loop(loop_stmt) => {
                self.emit_line("loop {");
                self.indent += 1;
                self.gen_block(&loop_stmt.body);
                self.indent -= 1;
                self.emit_line("}");
            }
            Stmt::Return(ret) => {
                self.emit_indent();
                if let Some(value) = &ret.value {
                    self.emit("return ");
                    self.gen_expr(value);
                    self.emit(";\n");
                } else {
                    self.emit("return;\n");
                }
            }
            Stmt::Break(_) => {
                self.emit_line("break;");
            }
            Stmt::Continue(_) => {
                self.emit_line("continue;");
            }
            Stmt::Traverse(traverse_stmt) => {
                self.gen_traverse_stmt(traverse_stmt);
            }
        }
    }

    fn gen_if_let_stmt(&mut self, if_stmt: &IfStmt, pattern: &Pattern) {
        // Generate if-let pattern matching for SWC/Rust
        self.emit_indent();
        self.emit("if let ");
        self.gen_pattern(pattern);
        self.emit(" = ");
        self.gen_expr(&if_stmt.condition);
        self.emit(" {\n");

        self.indent += 1;
        self.type_env.push_scope();

        // If pattern binds a variable, add it to the environment
        if let Pattern::Variant { name, inner } = pattern {
            if let Some(inner_pat) = inner {
                if let Pattern::Ident(binding) = inner_pat.as_ref() {
                    // For Some(x), the binding 'x' gets the inner type
                    // For now, use unknown type - could be improved with type inference
                    let ctx = TypeContext::unknown();
                    self.type_env.define(binding, ctx);
                }
            }
        } else if let Pattern::Ident(binding) = pattern {
            let ctx = TypeContext::unknown();
            self.type_env.define(binding, ctx);
        }

        self.gen_block(&if_stmt.then_branch);

        self.type_env.pop_scope();
        self.indent -= 1;

        // Handle else branch
        if let Some(else_block) = &if_stmt.else_branch {
            self.emit_indent();
            self.emit("} else {\n");
            self.indent += 1;
            self.gen_block(else_block);
            self.indent -= 1;
        }

        self.emit_line("}");
    }

    fn gen_traverse_stmt(&mut self, traverse_stmt: &crate::parser::TraverseStmt) {
        match &traverse_stmt.kind {
            crate::parser::TraverseKind::Inline(inline) => {
                // Generate a unique struct name for this inline visitor
                let struct_name = format!("__InlineVisitor_{}", self.hoisted_visitors.len());

                // Check if we have captures (need lifetime parameter)
                let has_captures = !traverse_stmt.captures.is_empty();
                let lifetime = if has_captures { "<'a>" } else { "" };

                // Build the hoisted struct definition
                let mut struct_def = String::new();
                struct_def.push_str(&format!("struct {}{} {{\n", struct_name, lifetime));

                // Add captured variables as reference fields
                for capture in &traverse_stmt.captures {
                    let ref_type = if capture.mutable {
                        "&'a mut"
                    } else {
                        "&'a"
                    };
                    // Look up type from environment, default to i32
                    // For simple integer variables initialized with literals, default to i32
                    let captured_type = if let Some(type_ctx) = self.type_env.lookup(&capture.name) {
                        if type_ctx.swc_type == "Unknown" {
                            "i32".to_string() // Default unknown types to i32
                        } else {
                            type_ctx.swc_type.clone()
                        }
                    } else {
                        "i32".to_string()
                    };
                    struct_def.push_str(&format!("    {}: {} {},\n", capture.name, ref_type, captured_type));
                }

                // Add local state fields
                for let_stmt in &inline.state {
                    let ty = if let Some(ref ty) = let_stmt.ty {
                        self.type_to_rust(ty)
                    } else {
                        "i32".to_string() // Default type, should be inferred
                    };
                    struct_def.push_str(&format!("    {}: {},\n", let_stmt.name, ty));
                }
                struct_def.push_str("}\n\n");

                // Generate impl VisitMut for the struct
                let impl_lifetime = if has_captures { "<'a>" } else { "" };
                struct_def.push_str(&format!("impl{} VisitMut for {}{} {{\n", impl_lifetime, struct_name, lifetime));
                for method in &inline.methods {
                    // Convert visit_xxx to visit_mut_xxx
                    let swc_method = self.visitor_method_to_swc(&method.name);

                    // Get parameter type
                    let param_type = if !method.params.is_empty() {
                        if let crate::parser::Type::Reference { inner, .. } = &method.params[0].ty {
                            if let crate::parser::Type::Named(name) = inner.as_ref() {
                                self.rustscript_type_to_swc(name)
                            } else {
                                "Expr".to_string()
                            }
                        } else {
                            "Expr".to_string()
                        }
                    } else {
                        "Expr".to_string()
                    };

                    // Get the original parameter name from the method
                    let param_name = if !method.params.is_empty() {
                        &method.params[0].name
                    } else {
                        "n"
                    };

                    struct_def.push_str(&format!("    fn {}(&mut self, {}: &mut {}) {{\n", swc_method, param_name, param_type));

                    // Generate method body with captured variables marked for self. prefix
                    let mut body_gen = SwcGenerator::new();
                    body_gen.indent = 2;
                    // Mark captured variables so they generate as self.var
                    for capture in &traverse_stmt.captures {
                        body_gen.captured_vars.insert(capture.name.clone());
                    }
                    // Also mark local state variables
                    for let_stmt in &inline.state {
                        body_gen.captured_vars.insert(let_stmt.name.clone());
                    }
                    body_gen.gen_block(&method.body);
                    struct_def.push_str(&body_gen.output);

                    struct_def.push_str("    }\n");
                }
                struct_def.push_str("}\n");

                self.hoisted_visitors.push(struct_def);

                // Generate instantiation and call at the usage site
                self.emit_indent();
                self.emit(&format!("let mut __visitor = {} {{\n", struct_name));
                self.indent += 1;

                // Initialize captured variables (pass references)
                for capture in &traverse_stmt.captures {
                    self.emit_indent();
                    self.emit(&capture.name);
                    self.emit(": ");
                    if capture.mutable {
                        self.emit("&mut ");
                    } else {
                        self.emit("&");
                    }
                    self.emit(&capture.name);
                    self.emit(",\n");
                }

                // Initialize local state
                for let_stmt in &inline.state {
                    self.emit_indent();
                    self.emit(&let_stmt.name);
                    self.emit(": ");
                    self.gen_expr(&let_stmt.init);
                    self.emit(",\n");
                }
                self.indent -= 1;
                self.emit_indent();
                self.emit("};\n");

                // Generate visit_mut_with call
                self.emit_indent();
                self.gen_expr(&traverse_stmt.target);
                self.emit(".visit_mut_with(&mut __visitor);\n");
            }
            crate::parser::TraverseKind::Delegated(visitor_name) => {
                // Generate delegation to another visitor
                self.emit_indent();
                self.emit(&format!("let mut __visitor = {}::default();\n", visitor_name));
                self.emit_indent();
                self.gen_expr(&traverse_stmt.target);
                self.emit(".visit_mut_with(&mut __visitor);\n");
            }
        }
    }

    fn visitor_method_to_swc(&self, method_name: &str) -> String {
        // Convert visit_xxx_yyy to visit_mut_xxx_yyy
        if let Some(stripped) = method_name.strip_prefix("visit_") {
            format!("visit_mut_{}", stripped)
        } else {
            method_name.to_string()
        }
    }

    fn rustscript_type_to_swc(&self, type_name: &str) -> String {
        // Use mapping module to convert RustScript AST types to SWC types
        get_node_mapping(type_name)
            .map(|m| m.swc.to_string())
            .unwrap_or_else(|| type_name.to_string())
    }

    /// Extract matches!(var, Type) pattern from an expression
    /// Returns (variable_name, type_name) if found
    fn extract_matches_pattern(&self, expr: &Expr) -> Option<(String, String)> {
        if let Expr::Call(call) = expr {
            if let Expr::Ident(ident) = call.callee.as_ref() {
                if ident.name == "matches!" && call.args.len() == 2 {
                    // First arg should be the variable
                    let var_name = if let Expr::Ident(id) = &call.args[0] {
                        id.name.clone()
                    } else {
                        return None;
                    };

                    // Second arg should be the type name
                    let type_name = if let Expr::Ident(id) = &call.args[1] {
                        id.name.clone()
                    } else {
                        return None;
                    };

                    return Some((var_name, type_name));
                }
            }
        }
        None
    }

    /// Infer the type of an expression based on context
    fn infer_type(&self, expr: &Expr) -> TypeContext {
        match expr {
            Expr::Ident(ident) => {
                // Look up variable type from environment
                self.type_env.lookup(&ident.name)
                    .cloned()
                    .unwrap_or(TypeContext::unknown())
            }

            Expr::Member(mem) => {
                // Get object type, then look up field type
                let obj_type = self.infer_type(&mem.object);
                if let Some(mapping) = get_typed_field_mapping(&obj_type.swc_type, &mem.property) {
                    let (_, kind) = map_rustscript_to_swc(mapping.result_type_rs);
                    TypeContext {
                        rustscript_type: mapping.result_type_rs.to_string(),
                        swc_type: mapping.result_type_swc.to_string(),
                        kind,
                        known_variant: None,
                        needs_deref: mapping.needs_deref,
                    }
                } else {
                    // Unknown field access
                    TypeContext::unknown()
                }
            }

            Expr::Call(call) => {
                // Check for .clone() which preserves type
                if let Expr::Member(mem) = call.callee.as_ref() {
                    if mem.property == "clone" && call.args.is_empty() {
                        return self.infer_type(&mem.object);
                    }
                }
                // Default: unknown return type
                TypeContext::unknown()
            }

            Expr::VecInit(_) => {
                // Vec initialization - could track element type but for now unknown
                TypeContext::unknown()
            }

            Expr::Ref(ref_expr) => {
                // Reference expression - infer the inner type
                self.infer_type(&ref_expr.expr)
            }

            _ => TypeContext::unknown(),
        }
    }

    /// Convert an AST type to a TypeContext
    fn type_from_ast(&self, ty: &Type) -> TypeContext {
        match ty {
            Type::Named(name) => TypeContext::from_rustscript(name),
            Type::Primitive(name) => TypeContext::from_rustscript(name),
            Type::Reference { inner, .. } => self.type_from_ast(inner),
            Type::Container { name, .. } => {
                // Handle Vec, Option, etc.
                TypeContext::from_rustscript(name)
            }
            Type::Array { element } => {
                let _elem_type = self.type_from_ast(element);
                TypeContext::unknown() // Array type - could be improved
            }
            Type::Tuple(_) => TypeContext::unknown(),
            Type::Optional(inner) => self.type_from_ast(inner),
            Type::Unit => TypeContext::unknown(),
        }
    }

    /// Get the element type from a collection type (Vec, array, etc.)
    fn get_element_type(&self, container_type: &TypeContext) -> TypeContext {
        // Check if the swc_type represents a Vec or array
        let swc_type = &container_type.swc_type;

        // Handle Vec<T> - extract T
        if swc_type.starts_with("Vec<") && swc_type.ends_with(">") {
            let inner = &swc_type[4..swc_type.len()-1];
            return TypeContext {
                rustscript_type: inner.to_string(),
                swc_type: inner.to_string(),
                kind: super::type_context::classify_swc_type(inner),
                known_variant: None,
                needs_deref: false,
            };
        }

        // For unknown collections, return unknown
        TypeContext::unknown()
    }

    fn gen_pattern(&mut self, pattern: &Pattern) {
        match pattern {
            Pattern::Literal(lit) => self.gen_literal(lit),
            Pattern::Ident(name) => self.emit(name),
            Pattern::Wildcard => self.emit("_"),
            Pattern::Struct { name, fields } => {
                self.emit(name);
                self.emit(" { ");
                for (i, (fname, fpat)) in fields.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }
                    self.emit(fname);
                    self.emit(": ");
                    self.gen_pattern(fpat);
                }
                self.emit(" }");
            }
            Pattern::Variant { name, inner } => {
                self.emit(name);
                if let Some(inner_pat) = inner {
                    self.emit("(");
                    self.gen_pattern(inner_pat);
                    self.emit(")");
                }
            }
            Pattern::Or(patterns) => {
                for (i, p) in patterns.iter().enumerate() {
                    if i > 0 {
                        self.emit(" | ");
                    }
                    self.gen_pattern(p);
                }
            }
        }
    }

    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Literal(lit) => self.gen_literal(lit),
            Expr::Ident(ident) => {
                match ident.name.as_str() {
                    "self" => self.emit("self"),
                    _ => {
                        // Check for parameter renames (e.g., "node" -> "n")
                        let output = if let Some(renamed) = self.param_renames.get(&ident.name) {
                            renamed.clone()
                        } else {
                            ident.name.clone()
                        };
                        // Check if this is a captured variable (needs self. prefix)
                        if self.captured_vars.contains(&ident.name) {
                            self.emit(&format!("self.{}", output));
                        } else {
                            self.emit(&output);
                        }
                    }
                }
            }
            Expr::Binary(bin) => {
                self.emit("(");
                self.gen_expr(&bin.left);
                self.emit(&format!(" {} ", self.binary_op_to_rust(&bin.op)));
                self.gen_expr(&bin.right);
                self.emit(")");
            }
            Expr::Unary(un) => {
                match un.op {
                    UnaryOp::Not => {
                        self.emit("!");
                        self.gen_expr(&un.operand);
                    }
                    UnaryOp::Neg => {
                        self.emit("-");
                        self.gen_expr(&un.operand);
                    }
                    UnaryOp::Deref => {
                        self.emit("*");
                        self.gen_expr(&un.operand);
                    }
                    UnaryOp::Ref => {
                        self.emit("&");
                        self.gen_expr(&un.operand);
                    }
                    UnaryOp::RefMut => {
                        self.emit("&mut ");
                        self.gen_expr(&un.operand);
                    }
                }
            }
            Expr::Call(call) => {
                // Check for matches! macro
                if let Expr::Ident(ident) = call.callee.as_ref() {
                    if ident.name == "matches!" && call.args.len() >= 2 {
                        self.gen_matches_macro(&call.args[0], &call.args[1]);
                        return;
                    }
                    // Check for format! macro - pass through as-is
                    if ident.name == "format" && !call.args.is_empty() {
                        self.emit("format!(");
                        for (i, arg) in call.args.iter().enumerate() {
                            if i > 0 {
                                self.emit(", ");
                            }
                            self.gen_expr(arg);
                        }
                        self.emit(")");
                        return;
                    }
                }

                // Check for visitor traversal methods
                if let Expr::Member(mem) = call.callee.as_ref() {
                    let prop = &mem.property;
                    // visit_children(self) -> n.visit_mut_children_with(self)
                    if prop == "visit_children" {
                        self.gen_expr(&mem.object);
                        self.emit(".visit_mut_children_with(self)");
                        return;
                    }
                    // visit_with(self) -> n.visit_mut_with(self)
                    if prop == "visit_with" {
                        self.gen_expr(&mem.object);
                        self.emit(".visit_mut_with(self)");
                        return;
                    }
                }

                self.gen_expr(&call.callee);
                self.emit("(");
                for (i, arg) in call.args.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }
                    self.gen_expr(arg);
                }
                self.emit(")");
            }
            Expr::Member(mem) => {
                // Check for nested member access that needs unwrapping
                // e.g., node.callee.name or member.key.name
                if mem.property == "name" || mem.property == "sym" {
                    if let Expr::Member(inner) = mem.object.as_ref() {
                        let inner_prop = &inner.property;
                        // Handle callee.name -> need to unwrap Callee::Expr then Expr::Ident
                        if inner_prop == "callee" {
                            // Generate: if let Callee::Expr(e) = &obj.callee { if let Expr::Ident(i) = e.as_ref() { i.sym.clone() } }
                            // For now, emit a simpler pattern that assumes Ident
                            self.emit("{ let __callee = &");
                            self.gen_expr(&inner.object);
                            self.emit(".callee; match __callee { Callee::Expr(e) => match e.as_ref() { Expr::Ident(i) => i.sym.clone(), _ => \"\".into() }, _ => \"\".into() } }");
                            return;
                        }
                        // Handle key.name -> need to unwrap Box<Expr> then Expr::Ident
                        if inner_prop == "key" {
                            self.emit("{ match ");
                            self.gen_expr(&inner.object);
                            self.emit(".key.as_ref() { Expr::Ident(i) => i.sym.clone(), _ => \"\".into() } }");
                            return;
                        }
                    }
                }

                // Simple member access
                self.gen_expr(&mem.object);
                self.emit(".");
                // Map RustScript field names to SWC field names
                let swc_field = match mem.property.as_str() {
                    // Identifier.name -> Ident.sym
                    "name" => "sym",
                    // MemberExpression.property -> MemberExpr.prop
                    "property" => "prop",
                    // MemberExpression.object -> MemberExpr.obj (needs Box unwrap)
                    "object" => "obj",
                    // CallExpression.arguments -> CallExpr.args
                    "arguments" => "args",
                    // CallExpression.callee -> CallExpr.callee (needs Box unwrap)
                    "callee" => "callee",
                    _ => &mem.property,
                };
                self.emit(swc_field);
            }
            Expr::Index(idx) => {
                self.gen_expr(&idx.object);
                self.emit("[");
                self.gen_expr(&idx.index);
                self.emit("]");
            }
            Expr::StructInit(init) => {
                // Map RustScript AST types to SWC types
                // Don't lowercase - preserve original case for user-defined types
                let swc_type = self.rustscript_to_swc_type(&init.name);

                // Handle special SWC struct field mappings
                let is_ident = swc_type == "Ident";
                let is_call_expr = swc_type == "CallExpr";
                let is_literal = swc_type == "Lit";

                self.emit(&swc_type);
                self.emit(" { ");

                for (i, (name, value)) in init.fields.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }

                    // Map field names for SWC types
                    if is_ident && name == "name" {
                        self.emit("sym: ");
                        self.gen_expr(value);
                        self.emit(".into(), span: DUMMY_SP");
                    } else if is_call_expr && name == "callee" {
                        // CallExpr.callee is Callee enum
                        self.emit("callee: Callee::Expr(Box::new(Expr::Ident(Ident { sym: ");
                        // Extract the name from the nested Identifier
                        if let Expr::StructInit(nested) = value {
                            for (nested_name, nested_val) in &nested.fields {
                                if nested_name == "name" {
                                    self.gen_expr(nested_val);
                                }
                            }
                        } else {
                            self.gen_expr(value);
                        }
                        self.emit(".into(), span: DUMMY_SP, ..Default::default() })))");
                    } else if is_call_expr && name == "arguments" {
                        // CallExpr.args is Vec<ExprOrSpread>
                        self.emit("args: vec![]"); // Simplified for now
                        // TODO: properly handle ExprOrSpread
                    } else if is_literal && name == "value" {
                        // Literal needs proper Lit enum variant
                        self.emit("value: Lit::Num(Number { value: ");
                        self.gen_expr(value);
                        self.emit(".0, span: DUMMY_SP, raw: None })");
                    } else {
                        self.emit(name);
                        self.emit(": ");
                        self.gen_expr(value);
                    }
                }

                // Add required fields for CallExpr
                if is_call_expr {
                    self.emit(", span: DUMMY_SP, ..Default::default()");
                }

                self.emit(" }");
            }
            Expr::VecInit(vec) => {
                self.emit("vec![");
                for (i, elem) in vec.elements.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }
                    self.gen_expr(elem);
                }
                self.emit("]");
            }
            Expr::If(if_expr) => {
                self.emit("if ");
                self.gen_expr(&if_expr.condition);
                self.emit(" { ");
                for stmt in &if_expr.then_branch.stmts {
                    self.gen_stmt(stmt);
                }
                self.emit(" }");
                if let Some(else_block) = &if_expr.else_branch {
                    self.emit(" else { ");
                    for stmt in &else_block.stmts {
                        self.gen_stmt(stmt);
                    }
                    self.emit(" }");
                }
            }
            Expr::Match(match_expr) => {
                self.emit("match ");
                self.gen_expr(&match_expr.scrutinee);
                self.emit(" { ");
                for arm in &match_expr.arms {
                    self.gen_pattern(&arm.pattern);
                    self.emit(" => ");
                    self.gen_expr(&arm.body);
                    self.emit(", ");
                }
                self.emit("}");
            }
            Expr::Closure(closure) => {
                self.emit("|");
                self.emit(&closure.params.join(", "));
                self.emit("| ");
                self.gen_expr(&closure.body);
            }
            Expr::Ref(ref_expr) => {
                if ref_expr.mutable {
                    self.emit("&mut ");
                } else {
                    self.emit("&");
                }
                self.gen_expr(&ref_expr.expr);
            }
            Expr::Deref(deref) => {
                self.emit("*");
                self.gen_expr(&deref.expr);
            }
            Expr::Assign(assign) => {
                self.gen_expr(&assign.target);
                self.emit(" = ");
                self.gen_expr(&assign.value);
            }
            Expr::CompoundAssign(compound) => {
                self.gen_expr(&compound.target);
                self.emit(&format!(" {}= ", self.compound_op_to_rust(&compound.op)));
                self.gen_expr(&compound.value);
            }
            Expr::Range(range) => {
                if let Some(start) = &range.start {
                    self.gen_expr(start);
                }
                if range.inclusive {
                    self.emit("..=");
                } else {
                    self.emit("..");
                }
                if let Some(end) = &range.end {
                    self.gen_expr(end);
                }
            }
            Expr::Paren(inner) => {
                self.emit("(");
                self.gen_expr(inner);
                self.emit(")");
            }
        }
    }

    fn gen_literal(&mut self, lit: &Literal) {
        match lit {
            Literal::String(s) => {
                self.emit(&format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")));
            }
            Literal::Int(n) => {
                self.emit(&n.to_string());
            }
            Literal::Float(n) => {
                self.emit(&n.to_string());
            }
            Literal::Bool(b) => {
                self.emit(if *b { "true" } else { "false" });
            }
            Literal::Null => {
                self.emit("None");
            }
        }
    }

    fn binary_op_to_rust(&self, op: &BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            BinaryOp::Div => "/",
            BinaryOp::Mod => "%",
            BinaryOp::Eq => "==",
            BinaryOp::NotEq => "!=",
            BinaryOp::Lt => "<",
            BinaryOp::Gt => ">",
            BinaryOp::LtEq => "<=",
            BinaryOp::GtEq => ">=",
            BinaryOp::And => "&&",
            BinaryOp::Or => "||",
        }
    }

    fn compound_op_to_rust(&self, op: &CompoundAssignOp) -> &'static str {
        match op {
            CompoundAssignOp::AddAssign => "+",
            CompoundAssignOp::SubAssign => "-",
            CompoundAssignOp::MulAssign => "*",
            CompoundAssignOp::DivAssign => "/",
        }
    }

    /// Generate matches! macro for SWC
    fn gen_matches_macro(&mut self, scrutinee: &Expr, pattern: &Expr) {
        // For SWC, we generate a boolean expression with nested if-let patterns
        // For simplicity, we'll generate a simpler check that works for common cases
        self.emit("{\n");
        self.indent += 1;
        self.emit_indent();
        self.emit("let __matched = ");
        self.gen_swc_pattern_check(scrutinee, pattern, 0);
        self.emit(";\n");
        self.emit_indent();
        self.emit("__matched\n");
        self.indent -= 1;
        self.emit_indent();
        self.emit("}");
    }

    /// Generate SWC pattern checking code
    fn gen_swc_pattern_check(&mut self, scrutinee: &Expr, pattern: &Expr, depth: usize) {
        match pattern {
            Expr::StructInit(init) => {
                let swc_type = self.rustscript_to_swc_type(&init.name.to_lowercase());

                // For nested patterns, we need to check the type and fields
                // Generate: matches!(scrutinee, SomeType { .. }) && field checks

                self.emit("matches!(");
                self.gen_expr(scrutinee);
                self.emit(", ");

                // Use mapping module for SWC enum variants
                if let Some(mapping) = get_node_mapping(&init.name) {
                    // Use the swc_pattern from mapping (e.g., "Expr::Ident(ident)")
                    // but we need just the pattern without binding
                    let pattern = mapping.swc_pattern.replace(|c: char| c.is_lowercase() || c == '_', "");
                    let pattern = if pattern.ends_with("()") {
                        pattern.replace("()", "(_)")
                    } else {
                        format!("{}(_)", mapping.swc_pattern.split('(').next().unwrap_or(&mapping.swc_pattern))
                    };
                    self.emit(&pattern);
                } else if init.name == "StringLiteral" {
                    self.emit("Expr::Lit(Lit::Str(_))");
                } else {
                    self.emit(&format!("{}{{ .. }}", swc_type));
                }
                self.emit(")");

                // Generate field checks with && chains
                for (field_name, field_pattern) in &init.fields {
                    self.emit(" && ");

                    // Generate field access - need to unwrap the enum first
                    let unwrap_prefix = if let Some(mapping) = get_node_mapping(&init.name) {
                        // Generate: if let Pattern = &expr { ... }
                        format!("if let {} = &", mapping.swc_pattern)
                    } else {
                        String::new()
                    };

                    if !unwrap_prefix.is_empty() {
                        self.emit("{ ");
                        self.emit(&unwrap_prefix);
                        self.gen_expr(scrutinee);
                        self.emit(" { ");
                    }

                    let field_var = format!("__f{}", depth);
                    match field_pattern {
                        Expr::Literal(Literal::String(s)) => {
                            // String equality check on field
                            // Use field mapping to get correct SWC field name
                            let swc_field = get_field_mapping(&init.name, field_name)
                                .map(|m| m.swc)
                                .unwrap_or(field_name.as_str());

                            // Get the variable name from the pattern binding
                            let var_name = get_node_mapping(&init.name)
                                .map(|m| {
                                    // Extract binding name from pattern like "Expr::Ident(ident)" -> "ident"
                                    m.swc_pattern
                                        .split('(')
                                        .nth(1)
                                        .and_then(|s| s.strip_suffix(')'))
                                        .unwrap_or("n")
                                })
                                .unwrap_or("n");

                            self.emit(&format!("&*{}.{} == \"{}\"", var_name, swc_field, s));
                        }
                        Expr::StructInit(nested) => {
                            // Nested pattern - recursive check
                            // Get the variable name from the pattern binding
                            let obj_var = get_node_mapping(&init.name)
                                .map(|m| {
                                    m.swc_pattern
                                        .split('(')
                                        .nth(1)
                                        .and_then(|s| s.strip_suffix(')'))
                                        .unwrap_or("n")
                                })
                                .unwrap_or("n");

                            // Use field mapping for the field name
                            let swc_field = get_field_mapping(&init.name, field_name)
                                .map(|m| m.swc)
                                .unwrap_or(field_name.as_str());

                            // Handle MemberProp specially - it's not an Expr
                            if init.name == "MemberExpression" && field_name == "property" {
                                // MemberProp needs special handling
                                if nested.name == "Identifier" {
                                    // MemberProp::Ident
                                    self.emit(&format!("matches!({}.prop, MemberProp::Ident(_))", obj_var));
                                    // Check name if specified
                                    for (nested_field, nested_val) in &nested.fields {
                                        if nested_field == "name" {
                                            if let Expr::Literal(Literal::String(s)) = nested_val {
                                                self.emit(&format!(" && {{ if let MemberProp::Ident(id) = &{}.prop {{ &*id.sym == \"{}\" }} else {{ false }} }}", obj_var, s));
                                            }
                                        }
                                    }
                                } else {
                                    self.emit("true /* unsupported MemberProp pattern */");
                                }
                            } else {
                                // Create a synthetic expression for the field access
                                let field_access = Expr::Ident(IdentExpr {
                                    name: format!("(*{}.{})", obj_var, swc_field),
                                    span: crate::lexer::Span::new(0, 0, 0, 0),
                                });
                                self.gen_swc_pattern_check(&field_access, &Expr::StructInit(nested.clone()), depth + 1);
                            }
                        }
                        _ => {
                            self.emit("true");
                        }
                    }

                    if !unwrap_prefix.is_empty() {
                        self.emit(" } else { false } }");
                    }
                }
            }
            Expr::Ident(ident) => {
                // Type check for a simple type name (e.g., MemberExpression)
                let type_name = &ident.name;

                // Use mapping to get the correct SWC pattern
                if let Some(mapping) = get_node_mapping(type_name) {
                    // Generate: matches!(scrutinee, Expr::Member(_))
                    self.emit("matches!(");
                    self.gen_expr(scrutinee);
                    self.emit(", ");

                    // Extract just the pattern part (e.g., "Expr::Member(_)")
                    let pattern_str = mapping.swc_pattern;
                    // Replace any binding variable with _
                    let pattern = if pattern_str.contains('(') {
                        let parts: Vec<&str> = pattern_str.split('(').collect();
                        format!("{}(_)", parts[0])
                    } else {
                        format!("{}{{ .. }}", pattern_str)
                    };
                    self.emit(&pattern);
                    self.emit(")");
                } else {
                    // Fallback: try common mappings
                    let swc_pattern = match type_name.as_str() {
                        "MemberExpression" => "Expr::Member(_)",
                        "CallExpression" => "Expr::Call(_)",
                        "Identifier" => "Expr::Ident(_)",
                        "FunctionDeclaration" => "Decl::Fn(_)",
                        "VariableDeclaration" => "Decl::Var(_)",
                        "ReturnStatement" => "Stmt::Return(_)",
                        "IfStatement" => "Stmt::If(_)",
                        "BlockStatement" => "Stmt::Block(_)",
                        _ => {
                            // Generate a placeholder
                            self.gen_expr(scrutinee);
                            self.emit(&format!(".is_{}()", type_name.to_lowercase()));
                            return;
                        }
                    };
                    self.emit(&format!("matches!("));
                    self.gen_expr(scrutinee);
                    self.emit(&format!(", {})", swc_pattern));
                }
            }
            _ => {
                // Literal or other pattern - generate equality check
                self.gen_expr(scrutinee);
                self.emit(" == ");
                self.gen_expr(pattern);
            }
        }
    }
}

impl Default for SwcGenerator {
    fn default() -> Self {
        Self::new()
    }
}
