//! SWC (Rust) code generator for RustScript

use crate::parser::*;

/// Generator for SWC plugin Rust code
pub struct SwcGenerator {
    output: String,
    indent: usize,
    /// Maps RustScript parameter names to SWC names (e.g., "node" -> "n")
    param_renames: std::collections::HashMap<String, String>,
    /// Plugin name for generating nested visitors
    plugin_name: String,
    /// Hoisted inline visitor structs
    hoisted_visitors: Vec<String>,
}

impl SwcGenerator {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            param_renames: std::collections::HashMap::new(),
            plugin_name: String::new(),
            hoisted_visitors: Vec::new(),
        }
    }

    /// Generate Rust code for an SWC plugin
    pub fn generate(&mut self, program: &Program) -> String {
        // Emit file header
        self.emit_line("// Generated by RustScript compiler");
        self.emit_line("// Do not edit manually");
        self.emit_line("");
        self.emit_line("use swc_common::{Span, DUMMY_SP};");
        self.emit_line("use swc_ecma_ast::*;");
        self.emit_line("use swc_ecma_visit::{VisitMut, VisitMutWith};");
        self.emit_line("");

        match &program.decl {
            TopLevelDecl::Plugin(plugin) => self.gen_plugin(plugin),
            TopLevelDecl::Writer(writer) => self.gen_writer(writer),
        }

        // Emit hoisted inline visitors at the end
        if !self.hoisted_visitors.is_empty() {
            self.emit_line("");
            self.emit_line("// Hoisted inline visitors for traverse blocks");
            let visitors = std::mem::take(&mut self.hoisted_visitors);
            for visitor in visitors {
                self.emit(&visitor);
                self.emit_line("");
            }
        }

        std::mem::take(&mut self.output)
    }

    fn emit(&mut self, s: &str) {
        self.output.push_str(s);
    }

    fn emit_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
    }

    fn emit_line(&mut self, s: &str) {
        self.emit_indent();
        self.emit(s);
        self.emit("\n");
    }

    fn gen_plugin(&mut self, plugin: &PluginDecl) {
        // Generate struct definitions first
        for item in &plugin.body {
            if let PluginItem::Struct(s) = item {
                self.gen_struct(s);
            }
        }

        // Generate enum definitions
        for item in &plugin.body {
            if let PluginItem::Enum(e) = item {
                self.gen_enum(e);
            }
        }

        // Generate the main plugin struct
        self.emit_line(&format!("pub struct {} {{", plugin.name));
        self.indent += 1;
        self.emit_line("// Plugin state");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        // Generate impl block with helper functions
        self.emit_line(&format!("impl {} {{", plugin.name));
        self.indent += 1;

        self.emit_line("pub fn new() -> Self {");
        self.indent += 1;
        self.emit_line("Self {}");
        self.indent -= 1;
        self.emit_line("}");

        // Generate helper functions (non-visitor)
        for item in &plugin.body {
            if let PluginItem::Function(f) = item {
                if !f.name.starts_with("visit_") {
                    self.emit_line("");
                    self.gen_helper_function(f);
                }
            }
        }

        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        // Generate VisitMut impl
        self.emit_line(&format!("impl VisitMut for {} {{", plugin.name));
        self.indent += 1;

        for item in &plugin.body {
            if let PluginItem::Function(f) = item {
                if f.name.starts_with("visit_") {
                    self.gen_visitor_method(f);
                }
            }
        }

        self.indent -= 1;
        self.emit_line("}");
    }

    fn gen_writer(&mut self, writer: &WriterDecl) {
        // For writers, use Visit instead of VisitMut
        self.emit_line("use swc_ecma_visit::Visit;");
        self.emit_line("");

        // Generate structs
        for item in &writer.body {
            if let PluginItem::Struct(s) = item {
                self.gen_struct(s);
            }
        }

        // Generate the writer struct with CodeBuilder
        self.emit_line(&format!("pub struct {} {{", writer.name));
        self.indent += 1;
        self.emit_line("output: String,");
        self.emit_line("indent_level: usize,");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        // Generate impl block
        self.emit_line(&format!("impl {} {{", writer.name));
        self.indent += 1;

        self.emit_line("pub fn new() -> Self {");
        self.indent += 1;
        self.emit_line("Self {");
        self.indent += 1;
        self.emit_line("output: String::new(),");
        self.emit_line("indent_level: 0,");
        self.indent -= 1;
        self.emit_line("}");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        // CodeBuilder methods
        self.emit_line("fn append(&mut self, s: &str) {");
        self.indent += 1;
        self.emit_line("self.output.push_str(s);");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        self.emit_line("fn newline(&mut self) {");
        self.indent += 1;
        self.emit_line("self.output.push('\\n');");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        self.emit_line("fn indent(&mut self) {");
        self.indent += 1;
        self.emit_line("self.indent_level += 1;");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        self.emit_line("fn dedent(&mut self) {");
        self.indent += 1;
        self.emit_line("self.indent_level -= 1;");
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        self.emit_line("pub fn finish(self) -> String {");
        self.indent += 1;
        self.emit_line("self.output");
        self.indent -= 1;
        self.emit_line("}");

        // Generate helper functions
        for item in &writer.body {
            if let PluginItem::Function(f) = item {
                if !f.name.starts_with("visit_") {
                    self.emit_line("");
                    self.gen_helper_function(f);
                }
            }
        }

        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        // Generate Visit impl
        self.emit_line(&format!("impl Visit for {} {{", writer.name));
        self.indent += 1;

        for item in &writer.body {
            if let PluginItem::Function(f) = item {
                if f.name.starts_with("visit_") {
                    self.gen_visit_method(f);
                }
            }
        }

        self.indent -= 1;
        self.emit_line("}");
    }

    fn gen_struct(&mut self, s: &StructDecl) {
        self.emit_line("#[derive(Debug, Clone)]");
        self.emit_line(&format!("pub struct {} {{", s.name));
        self.indent += 1;
        for field in &s.fields {
            self.emit_indent();
            self.emit(&format!("pub {}: {},\n", field.name, self.type_to_rust(&field.ty)));
        }
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");
    }

    fn gen_enum(&mut self, e: &EnumDecl) {
        self.emit_line("#[derive(Debug, Clone)]");
        self.emit_line(&format!("pub enum {} {{", e.name));
        self.indent += 1;
        for variant in &e.variants {
            self.emit_indent();
            if let Some(fields) = &variant.fields {
                let types: Vec<String> = fields.iter().map(|t| self.type_to_rust(t)).collect();
                self.emit(&format!("{}({}),\n", variant.name, types.join(", ")));
            } else {
                self.emit(&format!("{},\n", variant.name));
            }
        }
        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");
    }

    fn gen_helper_function(&mut self, f: &FnDecl) {
        let pub_str = if f.is_pub { "pub " } else { "" };
        let params: Vec<String> = f.params.iter().map(|p| {
            format!("{}: {}", p.name, self.type_to_rust(&p.ty))
        }).collect();

        let ret_type = f.return_type.as_ref()
            .map(|t| format!(" -> {}", self.type_to_rust(t)))
            .unwrap_or_default();

        self.emit_line(&format!("{}fn {}({}){} {{", pub_str, f.name, params.join(", "), ret_type));
        self.indent += 1;
        self.gen_block(&f.body);
        self.indent -= 1;
        self.emit_line("}");
    }

    fn gen_visitor_method(&mut self, f: &FnDecl) {
        let swc_name = self.visitor_name_to_swc(&f.name);
        let swc_type = self.visitor_name_to_swc_type(&f.name);

        self.emit_line("");
        self.emit_line(&format!("fn {}(&mut self, n: &mut {}) {{", swc_name, swc_type));
        self.indent += 1;

        // Set up parameter renames for visitor methods
        // The first parameter (typically "node") maps to "n"
        if let Some(first_param) = f.params.first() {
            self.param_renames.insert(first_param.name.clone(), "n".to_string());
        }

        // Generate body
        self.gen_block(&f.body);

        // Clear renames
        self.param_renames.clear();

        self.indent -= 1;
        self.emit_line("}");
    }

    fn gen_visit_method(&mut self, f: &FnDecl) {
        // For Visit (read-only), parameters are & not &mut
        let swc_name = self.visitor_name_to_swc(&f.name);
        let swc_type = self.visitor_name_to_swc_type(&f.name);

        self.emit_line("");
        self.emit_line(&format!("fn {}(&mut self, n: &{}) {{", swc_name, swc_type));
        self.indent += 1;

        self.gen_block(&f.body);

        self.indent -= 1;
        self.emit_line("}");
    }

    fn visitor_name_to_swc(&self, name: &str) -> String {
        // visit_call_expression -> visit_mut_call_expr
        let stripped = name.strip_prefix("visit_").unwrap_or(name);
        format!("visit_mut_{}", self.to_swc_node_name(stripped))
    }

    fn visitor_name_to_swc_type(&self, name: &str) -> String {
        let stripped = name.strip_prefix("visit_").unwrap_or(name);
        self.rustscript_to_swc_type(stripped)
    }

    fn to_swc_node_name(&self, name: &str) -> String {
        // Convert RustScript node names to SWC visitor method names
        match name {
            "call_expression" => "call_expr".to_string(),
            "member_expression" => "member_expr".to_string(),
            "binary_expression" => "bin_expr".to_string(),
            "unary_expression" => "unary_expr".to_string(),
            "function_declaration" => "fn_decl".to_string(),
            "variable_declaration" => "var_decl".to_string(),
            "if_statement" => "if_stmt".to_string(),
            "return_statement" => "return_stmt".to_string(),
            "block_statement" => "block_stmt".to_string(),
            "expression_statement" => "expr_stmt".to_string(),
            "for_statement" => "for_stmt".to_string(),
            "while_statement" => "while_stmt".to_string(),
            "jsx_element" => "jsx_element".to_string(),
            "jsx_attribute" => "jsx_attr".to_string(),
            _ => name.to_string(),
        }
    }

    fn rustscript_to_swc_type(&self, name: &str) -> String {
        // Convert RustScript node names to SWC AST types
        // Handle both snake_case and PascalCase inputs
        match name.to_lowercase().as_str() {
            "call_expression" | "callexpression" => "CallExpr".to_string(),
            "member_expression" | "memberexpression" => "MemberExpr".to_string(),
            "binary_expression" | "binaryexpression" => "BinExpr".to_string(),
            "unary_expression" | "unaryexpression" => "UnaryExpr".to_string(),
            "function_declaration" | "functiondeclaration" => "FnDecl".to_string(),
            "variable_declaration" | "variabledeclaration" => "VarDecl".to_string(),
            "if_statement" | "ifstatement" => "IfStmt".to_string(),
            "return_statement" | "returnstatement" => "ReturnStmt".to_string(),
            "block_statement" | "blockstatement" => "BlockStmt".to_string(),
            "expression_statement" | "expressionstatement" => "ExprStmt".to_string(),
            "for_statement" | "forstatement" => "ForStmt".to_string(),
            "while_statement" | "whilestatement" => "WhileStmt".to_string(),
            "identifier" => "Ident".to_string(),
            "jsx_element" | "jsxelement" => "JSXElement".to_string(),
            "jsx_attribute" | "jsxattribute" => "JSXAttr".to_string(),
            "program" => "Program".to_string(),
            "literal" => "Lit".to_string(),
            _ => {
                // Convert snake_case to PascalCase for unknown types
                name.split('_')
                    .map(|s| {
                        let mut chars = s.chars();
                        match chars.next() {
                            None => String::new(),
                            Some(c) => c.to_uppercase().chain(chars).collect(),
                        }
                    })
                    .collect()
            }
        }
    }

    fn type_to_rust(&self, ty: &Type) -> String {
        match ty {
            Type::Primitive(name) => {
                match name.as_str() {
                    "Str" => "String".to_string(),
                    "()" => "()".to_string(),
                    _ => name.clone(),
                }
            }
            Type::Reference { mutable, inner } => {
                let inner_type = self.type_to_rust(inner);
                if *mutable {
                    format!("&mut {}", inner_type)
                } else {
                    format!("&{}", inner_type)
                }
            }
            Type::Container { name, type_args } => {
                let args: Vec<String> = type_args.iter().map(|t| self.type_to_rust(t)).collect();
                format!("{}<{}>", name, args.join(", "))
            }
            Type::Named(name) => {
                // Map RustScript AST types to SWC types
                self.rustscript_to_swc_type(&name.to_lowercase())
            }
        }
    }

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.gen_stmt(stmt);
        }
    }

    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(let_stmt) => {
                self.emit_indent();
                if let_stmt.mutable {
                    self.emit("let mut ");
                } else {
                    self.emit("let ");
                }
                self.emit(&let_stmt.name);
                if let Some(ty) = &let_stmt.ty {
                    self.emit(&format!(": {}", self.type_to_rust(ty)));
                }
                self.emit(" = ");
                self.gen_expr(&let_stmt.init);
                self.emit(";\n");
            }
            Stmt::Const(const_stmt) => {
                self.emit_indent();
                self.emit("const ");
                self.emit(&const_stmt.name);
                if let Some(ty) = &const_stmt.ty {
                    self.emit(&format!(": {}", self.type_to_rust(ty)));
                }
                self.emit(" = ");
                self.gen_expr(&const_stmt.init);
                self.emit(";\n");
            }
            Stmt::Expr(expr_stmt) => {
                self.emit_indent();
                self.gen_expr(&expr_stmt.expr);
                self.emit(";\n");
            }
            Stmt::If(if_stmt) => {
                self.emit_indent();
                self.emit("if ");
                self.gen_expr(&if_stmt.condition);
                self.emit(" {\n");
                self.indent += 1;
                self.gen_block(&if_stmt.then_branch);
                self.indent -= 1;

                for (cond, block) in &if_stmt.else_if_branches {
                    self.emit_indent();
                    self.emit("} else if ");
                    self.gen_expr(cond);
                    self.emit(" {\n");
                    self.indent += 1;
                    self.gen_block(block);
                    self.indent -= 1;
                }

                if let Some(else_block) = &if_stmt.else_branch {
                    self.emit_indent();
                    self.emit("} else {\n");
                    self.indent += 1;
                    self.gen_block(else_block);
                    self.indent -= 1;
                }

                self.emit_line("}");
            }
            Stmt::Match(match_stmt) => {
                self.emit_indent();
                self.emit("match ");
                self.gen_expr(&match_stmt.scrutinee);
                self.emit(" {\n");
                self.indent += 1;
                for arm in &match_stmt.arms {
                    self.emit_indent();
                    self.gen_pattern(&arm.pattern);
                    self.emit(" => ");
                    self.gen_expr(&arm.body);
                    self.emit(",\n");
                }
                self.indent -= 1;
                self.emit_line("}");
            }
            Stmt::For(for_stmt) => {
                self.emit_indent();
                self.emit(&format!("for {} in ", for_stmt.var));
                self.gen_expr(&for_stmt.iter);
                self.emit(" {\n");
                self.indent += 1;
                self.gen_block(&for_stmt.body);
                self.indent -= 1;
                self.emit_line("}");
            }
            Stmt::While(while_stmt) => {
                self.emit_indent();
                self.emit("while ");
                self.gen_expr(&while_stmt.condition);
                self.emit(" {\n");
                self.indent += 1;
                self.gen_block(&while_stmt.body);
                self.indent -= 1;
                self.emit_line("}");
            }
            Stmt::Loop(loop_stmt) => {
                self.emit_line("loop {");
                self.indent += 1;
                self.gen_block(&loop_stmt.body);
                self.indent -= 1;
                self.emit_line("}");
            }
            Stmt::Return(ret) => {
                self.emit_indent();
                if let Some(value) = &ret.value {
                    self.emit("return ");
                    self.gen_expr(value);
                    self.emit(";\n");
                } else {
                    self.emit("return;\n");
                }
            }
            Stmt::Break(_) => {
                self.emit_line("break;");
            }
            Stmt::Continue(_) => {
                self.emit_line("continue;");
            }
            Stmt::Traverse(traverse_stmt) => {
                self.gen_traverse_stmt(traverse_stmt);
            }
        }
    }

    fn gen_traverse_stmt(&mut self, traverse_stmt: &crate::parser::TraverseStmt) {
        match &traverse_stmt.kind {
            crate::parser::TraverseKind::Inline(inline) => {
                // Generate a unique struct name for this inline visitor
                let struct_name = format!("__InlineVisitor_{}", self.hoisted_visitors.len());

                // Build the hoisted struct definition
                let mut struct_def = String::new();
                struct_def.push_str(&format!("struct {} {{\n", struct_name));
                for let_stmt in &inline.state {
                    let ty = if let Some(ref ty) = let_stmt.ty {
                        self.type_to_rust(ty)
                    } else {
                        "i32".to_string() // Default type, should be inferred
                    };
                    struct_def.push_str(&format!("    {}: {},\n", let_stmt.name, ty));
                }
                struct_def.push_str("}\n\n");

                // Generate impl VisitMut for the struct
                struct_def.push_str(&format!("impl VisitMut for {} {{\n", struct_name));
                for method in &inline.methods {
                    // Convert visit_xxx to visit_mut_xxx
                    let swc_method = self.visitor_method_to_swc(&method.name);

                    // Get parameter type
                    let param_type = if !method.params.is_empty() {
                        if let crate::parser::Type::Reference { inner, .. } = &method.params[0].ty {
                            if let crate::parser::Type::Named(name) = inner.as_ref() {
                                self.rustscript_type_to_swc(name)
                            } else {
                                "Expr".to_string()
                            }
                        } else {
                            "Expr".to_string()
                        }
                    } else {
                        "Expr".to_string()
                    };

                    // Get the original parameter name from the method
                    let param_name = if !method.params.is_empty() {
                        &method.params[0].name
                    } else {
                        "n"
                    };

                    struct_def.push_str(&format!("    fn {}(&mut self, {}: &mut {}) {{\n", swc_method, param_name, param_type));

                    // Generate method body
                    let mut body_gen = SwcGenerator::new();
                    body_gen.indent = 2;
                    body_gen.gen_block(&method.body);
                    struct_def.push_str(&body_gen.output);

                    struct_def.push_str("    }\n");
                }
                struct_def.push_str("}\n");

                self.hoisted_visitors.push(struct_def);

                // Generate instantiation and call at the usage site
                self.emit_indent();
                self.emit(&format!("let mut __visitor = {} {{\n", struct_name));
                self.indent += 1;
                for let_stmt in &inline.state {
                    self.emit_indent();
                    self.emit(&let_stmt.name);
                    self.emit(": ");
                    self.gen_expr(&let_stmt.init);
                    self.emit(",\n");
                }
                self.indent -= 1;
                self.emit_indent();
                self.emit("};\n");

                // Generate visit_mut_with call
                self.emit_indent();
                self.gen_expr(&traverse_stmt.target);
                self.emit(".visit_mut_with(&mut __visitor);\n");
            }
            crate::parser::TraverseKind::Delegated(visitor_name) => {
                // Generate delegation to another visitor
                self.emit_indent();
                self.emit(&format!("let mut __visitor = {}::default();\n", visitor_name));
                self.emit_indent();
                self.gen_expr(&traverse_stmt.target);
                self.emit(".visit_mut_with(&mut __visitor);\n");
            }
        }
    }

    fn visitor_method_to_swc(&self, method_name: &str) -> String {
        // Convert visit_xxx_yyy to visit_mut_xxx_yyy
        if let Some(stripped) = method_name.strip_prefix("visit_") {
            format!("visit_mut_{}", stripped)
        } else {
            method_name.to_string()
        }
    }

    fn rustscript_type_to_swc(&self, type_name: &str) -> String {
        // Map RustScript AST types to SWC types
        match type_name {
            "FunctionDeclaration" => "FnDecl",
            "CallExpression" => "CallExpr",
            "MemberExpression" => "MemberExpr",
            "Identifier" => "Ident",
            "ReturnStatement" => "ReturnStmt",
            "IfStatement" => "IfStmt",
            "BlockStatement" => "BlockStmt",
            _ => type_name,
        }.to_string()
    }

    fn gen_pattern(&mut self, pattern: &Pattern) {
        match pattern {
            Pattern::Literal(lit) => self.gen_literal(lit),
            Pattern::Ident(name) => self.emit(name),
            Pattern::Wildcard => self.emit("_"),
            Pattern::Struct { name, fields } => {
                self.emit(name);
                self.emit(" { ");
                for (i, (fname, fpat)) in fields.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }
                    self.emit(fname);
                    self.emit(": ");
                    self.gen_pattern(fpat);
                }
                self.emit(" }");
            }
            Pattern::Or(patterns) => {
                for (i, p) in patterns.iter().enumerate() {
                    if i > 0 {
                        self.emit(" | ");
                    }
                    self.gen_pattern(p);
                }
            }
        }
    }

    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Literal(lit) => self.gen_literal(lit),
            Expr::Ident(ident) => {
                match ident.name.as_str() {
                    "self" => self.emit("self"),
                    _ => {
                        // Check for parameter renames (e.g., "node" -> "n")
                        let output = if let Some(renamed) = self.param_renames.get(&ident.name) {
                            renamed.clone()
                        } else {
                            ident.name.clone()
                        };
                        self.emit(&output);
                    }
                }
            }
            Expr::Binary(bin) => {
                self.emit("(");
                self.gen_expr(&bin.left);
                self.emit(&format!(" {} ", self.binary_op_to_rust(&bin.op)));
                self.gen_expr(&bin.right);
                self.emit(")");
            }
            Expr::Unary(un) => {
                match un.op {
                    UnaryOp::Not => {
                        self.emit("!");
                        self.gen_expr(&un.operand);
                    }
                    UnaryOp::Neg => {
                        self.emit("-");
                        self.gen_expr(&un.operand);
                    }
                    UnaryOp::Deref => {
                        self.emit("*");
                        self.gen_expr(&un.operand);
                    }
                    UnaryOp::Ref => {
                        self.emit("&");
                        self.gen_expr(&un.operand);
                    }
                    UnaryOp::RefMut => {
                        self.emit("&mut ");
                        self.gen_expr(&un.operand);
                    }
                }
            }
            Expr::Call(call) => {
                // Check for matches! macro
                if let Expr::Ident(ident) = call.callee.as_ref() {
                    if ident.name == "matches!" && call.args.len() >= 2 {
                        self.gen_matches_macro(&call.args[0], &call.args[1]);
                        return;
                    }
                }

                // Check for visitor traversal methods
                if let Expr::Member(mem) = call.callee.as_ref() {
                    let prop = &mem.property;
                    // visit_children(self) -> n.visit_mut_children_with(self)
                    if prop == "visit_children" {
                        self.gen_expr(&mem.object);
                        self.emit(".visit_mut_children_with(self)");
                        return;
                    }
                    // visit_with(self) -> n.visit_mut_with(self)
                    if prop == "visit_with" {
                        self.gen_expr(&mem.object);
                        self.emit(".visit_mut_with(self)");
                        return;
                    }
                }

                self.gen_expr(&call.callee);
                self.emit("(");
                for (i, arg) in call.args.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }
                    self.gen_expr(arg);
                }
                self.emit(")");
            }
            Expr::Member(mem) => {
                self.gen_expr(&mem.object);
                self.emit(".");
                // Map RustScript field names to SWC field names
                let swc_field = match mem.property.as_str() {
                    // Identifier.name -> Ident.sym
                    "name" => "sym",
                    _ => &mem.property,
                };
                self.emit(swc_field);
            }
            Expr::Index(idx) => {
                self.gen_expr(&idx.object);
                self.emit("[");
                self.gen_expr(&idx.index);
                self.emit("]");
            }
            Expr::StructInit(init) => {
                // Map RustScript AST types to SWC types
                let swc_type = self.rustscript_to_swc_type(&init.name.to_lowercase());

                // Handle special SWC struct field mappings
                let is_ident = swc_type == "Ident";
                let is_call_expr = swc_type == "CallExpr";
                let is_literal = swc_type == "Lit";

                self.emit(&swc_type);
                self.emit(" { ");

                for (i, (name, value)) in init.fields.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }

                    // Map field names for SWC types
                    if is_ident && name == "name" {
                        self.emit("sym: ");
                        self.gen_expr(value);
                        self.emit(".into(), span: DUMMY_SP");
                    } else if is_call_expr && name == "callee" {
                        // CallExpr.callee is Callee enum
                        self.emit("callee: Callee::Expr(Box::new(Expr::Ident(Ident { sym: ");
                        // Extract the name from the nested Identifier
                        if let Expr::StructInit(nested) = value {
                            for (nested_name, nested_val) in &nested.fields {
                                if nested_name == "name" {
                                    self.gen_expr(nested_val);
                                }
                            }
                        } else {
                            self.gen_expr(value);
                        }
                        self.emit(".into(), span: DUMMY_SP, ..Default::default() })))");
                    } else if is_call_expr && name == "arguments" {
                        // CallExpr.args is Vec<ExprOrSpread>
                        self.emit("args: vec![]"); // Simplified for now
                        // TODO: properly handle ExprOrSpread
                    } else if is_literal && name == "value" {
                        // Literal needs proper Lit enum variant
                        self.emit("value: Lit::Num(Number { value: ");
                        self.gen_expr(value);
                        self.emit(".0, span: DUMMY_SP, raw: None })");
                    } else {
                        self.emit(name);
                        self.emit(": ");
                        self.gen_expr(value);
                    }
                }

                // Add required fields for CallExpr
                if is_call_expr {
                    self.emit(", span: DUMMY_SP, ..Default::default()");
                }

                self.emit(" }");
            }
            Expr::VecInit(vec) => {
                self.emit("vec![");
                for (i, elem) in vec.elements.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }
                    self.gen_expr(elem);
                }
                self.emit("]");
            }
            Expr::If(if_expr) => {
                self.emit("if ");
                self.gen_expr(&if_expr.condition);
                self.emit(" { ");
                for stmt in &if_expr.then_branch.stmts {
                    self.gen_stmt(stmt);
                }
                self.emit(" }");
                if let Some(else_block) = &if_expr.else_branch {
                    self.emit(" else { ");
                    for stmt in &else_block.stmts {
                        self.gen_stmt(stmt);
                    }
                    self.emit(" }");
                }
            }
            Expr::Match(match_expr) => {
                self.emit("match ");
                self.gen_expr(&match_expr.scrutinee);
                self.emit(" { ");
                for arm in &match_expr.arms {
                    self.gen_pattern(&arm.pattern);
                    self.emit(" => ");
                    self.gen_expr(&arm.body);
                    self.emit(", ");
                }
                self.emit("}");
            }
            Expr::Closure(closure) => {
                self.emit("|");
                self.emit(&closure.params.join(", "));
                self.emit("| ");
                self.gen_expr(&closure.body);
            }
            Expr::Ref(ref_expr) => {
                if ref_expr.mutable {
                    self.emit("&mut ");
                } else {
                    self.emit("&");
                }
                self.gen_expr(&ref_expr.expr);
            }
            Expr::Deref(deref) => {
                self.emit("*");
                self.gen_expr(&deref.expr);
            }
            Expr::Assign(assign) => {
                self.gen_expr(&assign.target);
                self.emit(" = ");
                self.gen_expr(&assign.value);
            }
            Expr::CompoundAssign(compound) => {
                self.gen_expr(&compound.target);
                self.emit(&format!(" {}= ", self.compound_op_to_rust(&compound.op)));
                self.gen_expr(&compound.value);
            }
            Expr::Range(range) => {
                if let Some(start) = &range.start {
                    self.gen_expr(start);
                }
                if range.inclusive {
                    self.emit("..=");
                } else {
                    self.emit("..");
                }
                if let Some(end) = &range.end {
                    self.gen_expr(end);
                }
            }
            Expr::Paren(inner) => {
                self.emit("(");
                self.gen_expr(inner);
                self.emit(")");
            }
        }
    }

    fn gen_literal(&mut self, lit: &Literal) {
        match lit {
            Literal::String(s) => {
                self.emit(&format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")));
            }
            Literal::Int(n) => {
                self.emit(&n.to_string());
            }
            Literal::Float(n) => {
                self.emit(&n.to_string());
            }
            Literal::Bool(b) => {
                self.emit(if *b { "true" } else { "false" });
            }
            Literal::Null => {
                self.emit("None");
            }
        }
    }

    fn binary_op_to_rust(&self, op: &BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            BinaryOp::Div => "/",
            BinaryOp::Mod => "%",
            BinaryOp::Eq => "==",
            BinaryOp::NotEq => "!=",
            BinaryOp::Lt => "<",
            BinaryOp::Gt => ">",
            BinaryOp::LtEq => "<=",
            BinaryOp::GtEq => ">=",
            BinaryOp::And => "&&",
            BinaryOp::Or => "||",
        }
    }

    fn compound_op_to_rust(&self, op: &CompoundAssignOp) -> &'static str {
        match op {
            CompoundAssignOp::AddAssign => "+",
            CompoundAssignOp::SubAssign => "-",
            CompoundAssignOp::MulAssign => "*",
            CompoundAssignOp::DivAssign => "/",
        }
    }

    /// Generate matches! macro for SWC
    fn gen_matches_macro(&mut self, scrutinee: &Expr, pattern: &Expr) {
        // For SWC, we generate a boolean expression with nested if-let patterns
        // For simplicity, we'll generate a simpler check that works for common cases
        self.emit("{\n");
        self.indent += 1;
        self.emit_indent();
        self.emit("let __matched = ");
        self.gen_swc_pattern_check(scrutinee, pattern, 0);
        self.emit(";\n");
        self.emit_indent();
        self.emit("__matched\n");
        self.indent -= 1;
        self.emit_indent();
        self.emit("}");
    }

    /// Generate SWC pattern checking code
    fn gen_swc_pattern_check(&mut self, scrutinee: &Expr, pattern: &Expr, depth: usize) {
        match pattern {
            Expr::StructInit(init) => {
                let swc_type = self.rustscript_to_swc_type(&init.name.to_lowercase());

                // For nested patterns, we need to check the type and fields
                // Generate: matches!(scrutinee, SomeType { .. }) && field checks

                self.emit("matches!(");
                self.gen_expr(scrutinee);
                self.emit(", ");

                // Map RustScript types to SWC enum variants
                match init.name.as_str() {
                    "Identifier" => self.emit("Expr::Ident(_)"),
                    "MemberExpression" => self.emit("Expr::Member(_)"),
                    "CallExpression" => self.emit("Expr::Call(_)"),
                    "StringLiteral" => self.emit("Expr::Lit(Lit::Str(_))"),
                    _ => self.emit(&format!("{}{{ .. }}", swc_type)),
                }
                self.emit(")");

                // Generate field checks with && chains
                for (field_name, field_pattern) in &init.fields {
                    self.emit(" && ");

                    // Generate field access - need to unwrap the enum first
                    let unwrap_prefix = match init.name.as_str() {
                        "Identifier" => "if let Expr::Ident(id) = &",
                        "MemberExpression" => "if let Expr::Member(mem) = &",
                        _ => "",
                    };

                    if !unwrap_prefix.is_empty() {
                        self.emit("{ ");
                        self.emit(unwrap_prefix);
                        self.gen_expr(scrutinee);
                        self.emit(" { ");
                    }

                    let field_var = format!("__f{}", depth);
                    match field_pattern {
                        Expr::Literal(Literal::String(s)) => {
                            // String equality check on field
                            let swc_field = match field_name.as_str() {
                                "name" => "sym",
                                _ => field_name,
                            };
                            self.emit(&format!("&*{}.{} == \"{}\"",
                                if init.name == "Identifier" { "id" } else { "mem" },
                                swc_field, s));
                        }
                        Expr::StructInit(nested) => {
                            // Nested pattern - recursive check
                            let obj_var = if init.name == "MemberExpression" { "mem" } else { "id" };
                            let swc_field = match field_name.as_str() {
                                "object" => "obj",
                                "property" => "prop",
                                _ => field_name,
                            };

                            // Handle MemberProp specially - it's not an Expr
                            if init.name == "MemberExpression" && field_name == "property" {
                                // MemberProp needs special handling
                                if nested.name == "Identifier" {
                                    // MemberProp::Ident
                                    self.emit(&format!("matches!({}.prop, MemberProp::Ident(_))", obj_var));
                                    // Check name if specified
                                    for (nested_field, nested_val) in &nested.fields {
                                        if nested_field == "name" {
                                            if let Expr::Literal(Literal::String(s)) = nested_val {
                                                self.emit(&format!(" && {{ if let MemberProp::Ident(id) = &{}.prop {{ &*id.sym == \"{}\" }} else {{ false }} }}", obj_var, s));
                                            }
                                        }
                                    }
                                } else {
                                    self.emit("true /* unsupported MemberProp pattern */");
                                }
                            } else {
                                // Create a synthetic expression for the field access
                                let field_access = Expr::Ident(IdentExpr {
                                    name: format!("(*{}.{})", obj_var, swc_field),
                                    span: crate::lexer::Span::new(0, 0, 0, 0),
                                });
                                self.gen_swc_pattern_check(&field_access, &Expr::StructInit(nested.clone()), depth + 1);
                            }
                        }
                        _ => {
                            self.emit("true");
                        }
                    }

                    if !unwrap_prefix.is_empty() {
                        self.emit(" } else { false } }");
                    }
                }
            }
            _ => {
                // Simple equality check
                self.gen_expr(scrutinee);
                self.emit(" == ");
                self.gen_expr(pattern);
            }
        }
    }
}

impl Default for SwcGenerator {
    fn default() -> Self {
        Self::new()
    }
}
