// Generated by RustScript compiler
// Do not edit manually

module.exports = function({ types: t }) {

  function get_name(node) {
    const id = (/* ? */ node.id);
    Ok(id.name);
  }

  let state = {};

  return {
    visitor: {

    }
  };
};
