// Generated by RustScript compiler
// Do not edit manually

module.exports = function({ types: t }) {

  function test_unit() {
    const x = undefined;
    Ok(undefined);
  }

  let state = {};

  return {
    visitor: {

    }
  };
};
